// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: domain_inheritance_test.proto

package net.badata.protobuf.converter.proto;

public final class DomainInheritanceProto {
  private DomainInheritanceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface TestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.badata.protobuf.converter.proto.Test)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional int32 inheritedInt = 1;</code>
     */
    int getInheritedInt();

    /**
     * <code>optional float inheritedFloat = 2;</code>
     */
    float getInheritedFloat();

    /**
     * <code>optional int64 ownLong = 3;</code>
     */
    long getOwnLong();

    /**
     * <code>optional double ownDouble = 4;</code>
     */
    double getOwnDouble();
  }
  /**
   * Protobuf type {@code net.badata.protobuf.converter.proto.Test}
   */
  public  static final class Test extends
      com.google.protobuf.GeneratedMessageLite<
          Test, Test.Builder> implements
      // @@protoc_insertion_point(message_implements:net.badata.protobuf.converter.proto.Test)
      TestOrBuilder {
    private Test() {
    }
    public static final int INHERITEDINT_FIELD_NUMBER = 1;
    private int inheritedInt_;
    /**
     * <code>optional int32 inheritedInt = 1;</code>
     */
    public int getInheritedInt() {
      return inheritedInt_;
    }
    /**
     * <code>optional int32 inheritedInt = 1;</code>
     */
    private void setInheritedInt(int value) {
      
      inheritedInt_ = value;
    }
    /**
     * <code>optional int32 inheritedInt = 1;</code>
     */
    private void clearInheritedInt() {
      
      inheritedInt_ = 0;
    }

    public static final int INHERITEDFLOAT_FIELD_NUMBER = 2;
    private float inheritedFloat_;
    /**
     * <code>optional float inheritedFloat = 2;</code>
     */
    public float getInheritedFloat() {
      return inheritedFloat_;
    }
    /**
     * <code>optional float inheritedFloat = 2;</code>
     */
    private void setInheritedFloat(float value) {
      
      inheritedFloat_ = value;
    }
    /**
     * <code>optional float inheritedFloat = 2;</code>
     */
    private void clearInheritedFloat() {
      
      inheritedFloat_ = 0F;
    }

    public static final int OWNLONG_FIELD_NUMBER = 3;
    private long ownLong_;
    /**
     * <code>optional int64 ownLong = 3;</code>
     */
    public long getOwnLong() {
      return ownLong_;
    }
    /**
     * <code>optional int64 ownLong = 3;</code>
     */
    private void setOwnLong(long value) {
      
      ownLong_ = value;
    }
    /**
     * <code>optional int64 ownLong = 3;</code>
     */
    private void clearOwnLong() {
      
      ownLong_ = 0L;
    }

    public static final int OWNDOUBLE_FIELD_NUMBER = 4;
    private double ownDouble_;
    /**
     * <code>optional double ownDouble = 4;</code>
     */
    public double getOwnDouble() {
      return ownDouble_;
    }
    /**
     * <code>optional double ownDouble = 4;</code>
     */
    private void setOwnDouble(double value) {
      
      ownDouble_ = value;
    }
    /**
     * <code>optional double ownDouble = 4;</code>
     */
    private void clearOwnDouble() {
      
      ownDouble_ = 0D;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (inheritedInt_ != 0) {
        output.writeInt32(1, inheritedInt_);
      }
      if (inheritedFloat_ != 0F) {
        output.writeFloat(2, inheritedFloat_);
      }
      if (ownLong_ != 0L) {
        output.writeInt64(3, ownLong_);
      }
      if (ownDouble_ != 0D) {
        output.writeDouble(4, ownDouble_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (inheritedInt_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, inheritedInt_);
      }
      if (inheritedFloat_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, inheritedFloat_);
      }
      if (ownLong_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, ownLong_);
      }
      if (ownDouble_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, ownDouble_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static net.badata.protobuf.converter.proto.DomainInheritanceProto.Test parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.badata.protobuf.converter.proto.DomainInheritanceProto.Test parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.DomainInheritanceProto.Test parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.badata.protobuf.converter.proto.DomainInheritanceProto.Test parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.DomainInheritanceProto.Test parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.badata.protobuf.converter.proto.DomainInheritanceProto.Test parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.DomainInheritanceProto.Test parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static net.badata.protobuf.converter.proto.DomainInheritanceProto.Test parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.DomainInheritanceProto.Test parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.badata.protobuf.converter.proto.DomainInheritanceProto.Test parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.badata.protobuf.converter.proto.DomainInheritanceProto.Test prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code net.badata.protobuf.converter.proto.Test}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          net.badata.protobuf.converter.proto.DomainInheritanceProto.Test, Builder> implements
        // @@protoc_insertion_point(builder_implements:net.badata.protobuf.converter.proto.Test)
        net.badata.protobuf.converter.proto.DomainInheritanceProto.TestOrBuilder {
      // Construct using net.badata.protobuf.converter.proto.DomainInheritanceProto.Test.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional int32 inheritedInt = 1;</code>
       */
      public int getInheritedInt() {
        return instance.getInheritedInt();
      }
      /**
       * <code>optional int32 inheritedInt = 1;</code>
       */
      public Builder setInheritedInt(int value) {
        copyOnWrite();
        instance.setInheritedInt(value);
        return this;
      }
      /**
       * <code>optional int32 inheritedInt = 1;</code>
       */
      public Builder clearInheritedInt() {
        copyOnWrite();
        instance.clearInheritedInt();
        return this;
      }

      /**
       * <code>optional float inheritedFloat = 2;</code>
       */
      public float getInheritedFloat() {
        return instance.getInheritedFloat();
      }
      /**
       * <code>optional float inheritedFloat = 2;</code>
       */
      public Builder setInheritedFloat(float value) {
        copyOnWrite();
        instance.setInheritedFloat(value);
        return this;
      }
      /**
       * <code>optional float inheritedFloat = 2;</code>
       */
      public Builder clearInheritedFloat() {
        copyOnWrite();
        instance.clearInheritedFloat();
        return this;
      }

      /**
       * <code>optional int64 ownLong = 3;</code>
       */
      public long getOwnLong() {
        return instance.getOwnLong();
      }
      /**
       * <code>optional int64 ownLong = 3;</code>
       */
      public Builder setOwnLong(long value) {
        copyOnWrite();
        instance.setOwnLong(value);
        return this;
      }
      /**
       * <code>optional int64 ownLong = 3;</code>
       */
      public Builder clearOwnLong() {
        copyOnWrite();
        instance.clearOwnLong();
        return this;
      }

      /**
       * <code>optional double ownDouble = 4;</code>
       */
      public double getOwnDouble() {
        return instance.getOwnDouble();
      }
      /**
       * <code>optional double ownDouble = 4;</code>
       */
      public Builder setOwnDouble(double value) {
        copyOnWrite();
        instance.setOwnDouble(value);
        return this;
      }
      /**
       * <code>optional double ownDouble = 4;</code>
       */
      public Builder clearOwnDouble() {
        copyOnWrite();
        instance.clearOwnDouble();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:net.badata.protobuf.converter.proto.Test)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new net.badata.protobuf.converter.proto.DomainInheritanceProto.Test();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          net.badata.protobuf.converter.proto.DomainInheritanceProto.Test other = (net.badata.protobuf.converter.proto.DomainInheritanceProto.Test) arg1;
          inheritedInt_ = visitor.visitInt(inheritedInt_ != 0, inheritedInt_,
              other.inheritedInt_ != 0, other.inheritedInt_);
          inheritedFloat_ = visitor.visitFloat(inheritedFloat_ != 0F, inheritedFloat_,
              other.inheritedFloat_ != 0F, other.inheritedFloat_);
          ownLong_ = visitor.visitLong(ownLong_ != 0L, ownLong_,
              other.ownLong_ != 0L, other.ownLong_);
          ownDouble_ = visitor.visitDouble(ownDouble_ != 0D, ownDouble_,
              other.ownDouble_ != 0D, other.ownDouble_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {

                  inheritedInt_ = input.readInt32();
                  break;
                }
                case 21: {

                  inheritedFloat_ = input.readFloat();
                  break;
                }
                case 24: {

                  ownLong_ = input.readInt64();
                  break;
                }
                case 33: {

                  ownDouble_ = input.readDouble();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (net.badata.protobuf.converter.proto.DomainInheritanceProto.Test.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:net.badata.protobuf.converter.proto.Test)
    private static final net.badata.protobuf.converter.proto.DomainInheritanceProto.Test DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Test();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static net.badata.protobuf.converter.proto.DomainInheritanceProto.Test getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Test> PARSER;

    public static com.google.protobuf.Parser<Test> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
