// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mapping_test.proto

package net.badata.protobuf.converter.proto;

public final class MappingProto {
  private MappingProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface NestedTestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.badata.protobuf.converter.proto.NestedTest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string stringValue = 1;</code>
     */
    java.lang.String getStringValue();
    /**
     * <code>optional string stringValue = 1;</code>
     */
    com.google.protobuf.ByteString
        getStringValueBytes();
  }
  /**
   * Protobuf type {@code net.badata.protobuf.converter.proto.NestedTest}
   */
  public  static final class NestedTest extends
      com.google.protobuf.GeneratedMessageLite<
          NestedTest, NestedTest.Builder> implements
      // @@protoc_insertion_point(message_implements:net.badata.protobuf.converter.proto.NestedTest)
      NestedTestOrBuilder {
    private NestedTest() {
      stringValue_ = "";
    }
    public static final int STRINGVALUE_FIELD_NUMBER = 1;
    private java.lang.String stringValue_;
    /**
     * <code>optional string stringValue = 1;</code>
     */
    public java.lang.String getStringValue() {
      return stringValue_;
    }
    /**
     * <code>optional string stringValue = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStringValueBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(stringValue_);
    }
    /**
     * <code>optional string stringValue = 1;</code>
     */
    private void setStringValue(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      stringValue_ = value;
    }
    /**
     * <code>optional string stringValue = 1;</code>
     */
    private void clearStringValue() {
      
      stringValue_ = getDefaultInstance().getStringValue();
    }
    /**
     * <code>optional string stringValue = 1;</code>
     */
    private void setStringValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      stringValue_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!stringValue_.isEmpty()) {
        output.writeString(1, getStringValue());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!stringValue_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getStringValue());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static net.badata.protobuf.converter.proto.MappingProto.NestedTest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.badata.protobuf.converter.proto.MappingProto.NestedTest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.MappingProto.NestedTest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.badata.protobuf.converter.proto.MappingProto.NestedTest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.MappingProto.NestedTest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.badata.protobuf.converter.proto.MappingProto.NestedTest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.MappingProto.NestedTest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static net.badata.protobuf.converter.proto.MappingProto.NestedTest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.MappingProto.NestedTest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.badata.protobuf.converter.proto.MappingProto.NestedTest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.badata.protobuf.converter.proto.MappingProto.NestedTest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code net.badata.protobuf.converter.proto.NestedTest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          net.badata.protobuf.converter.proto.MappingProto.NestedTest, Builder> implements
        // @@protoc_insertion_point(builder_implements:net.badata.protobuf.converter.proto.NestedTest)
        net.badata.protobuf.converter.proto.MappingProto.NestedTestOrBuilder {
      // Construct using net.badata.protobuf.converter.proto.MappingProto.NestedTest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string stringValue = 1;</code>
       */
      public java.lang.String getStringValue() {
        return instance.getStringValue();
      }
      /**
       * <code>optional string stringValue = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStringValueBytes() {
        return instance.getStringValueBytes();
      }
      /**
       * <code>optional string stringValue = 1;</code>
       */
      public Builder setStringValue(
          java.lang.String value) {
        copyOnWrite();
        instance.setStringValue(value);
        return this;
      }
      /**
       * <code>optional string stringValue = 1;</code>
       */
      public Builder clearStringValue() {
        copyOnWrite();
        instance.clearStringValue();
        return this;
      }
      /**
       * <code>optional string stringValue = 1;</code>
       */
      public Builder setStringValueBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setStringValueBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:net.badata.protobuf.converter.proto.NestedTest)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new net.badata.protobuf.converter.proto.MappingProto.NestedTest();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          net.badata.protobuf.converter.proto.MappingProto.NestedTest other = (net.badata.protobuf.converter.proto.MappingProto.NestedTest) arg1;
          stringValue_ = visitor.visitString(!stringValue_.isEmpty(), stringValue_,
              !other.stringValue_.isEmpty(), other.stringValue_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  stringValue_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (net.badata.protobuf.converter.proto.MappingProto.NestedTest.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:net.badata.protobuf.converter.proto.NestedTest)
    private static final net.badata.protobuf.converter.proto.MappingProto.NestedTest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new NestedTest();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static net.badata.protobuf.converter.proto.MappingProto.NestedTest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<NestedTest> PARSER;

    public static com.google.protobuf.Parser<NestedTest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface MappingTestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.badata.protobuf.converter.proto.MappingTest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional int32 intValue = 1;</code>
     */
    int getIntValue();

    /**
     * <code>optional int64 longValue = 2;</code>
     */
    long getLongValue();

    /**
     * <code>optional float floatValue = 3;</code>
     */
    float getFloatValue();

    /**
     * <code>optional double doubleValue = 4;</code>
     */
    double getDoubleValue();

    /**
     * <code>optional bool booleanValue = 5;</code>
     */
    boolean getBooleanValue();

    /**
     * <code>optional string stringValue = 6;</code>
     */
    java.lang.String getStringValue();
    /**
     * <code>optional string stringValue = 6;</code>
     */
    com.google.protobuf.ByteString
        getStringValueBytes();

    /**
     * <code>optional .net.badata.protobuf.converter.proto.NestedTest nestedValue = 7;</code>
     */
    boolean hasNestedValue();
    /**
     * <code>optional .net.badata.protobuf.converter.proto.NestedTest nestedValue = 7;</code>
     */
    net.badata.protobuf.converter.proto.MappingProto.NestedTest getNestedValue();

    /**
     * <code>repeated string stringListValue = 8;</code>
     */
    java.util.List<String>
        getStringListValueList();
    /**
     * <code>repeated string stringListValue = 8;</code>
     */
    int getStringListValueCount();
    /**
     * <code>repeated string stringListValue = 8;</code>
     */
    java.lang.String getStringListValue(int index);
    /**
     * <code>repeated string stringListValue = 8;</code>
     */
    com.google.protobuf.ByteString
        getStringListValueBytes(int index);

    /**
     * <code>repeated .net.badata.protobuf.converter.proto.NestedTest nestedListValue = 9;</code>
     */
    java.util.List<net.badata.protobuf.converter.proto.MappingProto.NestedTest> 
        getNestedListValueList();
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.NestedTest nestedListValue = 9;</code>
     */
    net.badata.protobuf.converter.proto.MappingProto.NestedTest getNestedListValue(int index);
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.NestedTest nestedListValue = 9;</code>
     */
    int getNestedListValueCount();
  }
  /**
   * Protobuf type {@code net.badata.protobuf.converter.proto.MappingTest}
   */
  public  static final class MappingTest extends
      com.google.protobuf.GeneratedMessageLite<
          MappingTest, MappingTest.Builder> implements
      // @@protoc_insertion_point(message_implements:net.badata.protobuf.converter.proto.MappingTest)
      MappingTestOrBuilder {
    private MappingTest() {
      stringValue_ = "";
      stringListValue_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
      nestedListValue_ = emptyProtobufList();
    }
    private int bitField0_;
    public static final int INTVALUE_FIELD_NUMBER = 1;
    private int intValue_;
    /**
     * <code>optional int32 intValue = 1;</code>
     */
    public int getIntValue() {
      return intValue_;
    }
    /**
     * <code>optional int32 intValue = 1;</code>
     */
    private void setIntValue(int value) {
      
      intValue_ = value;
    }
    /**
     * <code>optional int32 intValue = 1;</code>
     */
    private void clearIntValue() {
      
      intValue_ = 0;
    }

    public static final int LONGVALUE_FIELD_NUMBER = 2;
    private long longValue_;
    /**
     * <code>optional int64 longValue = 2;</code>
     */
    public long getLongValue() {
      return longValue_;
    }
    /**
     * <code>optional int64 longValue = 2;</code>
     */
    private void setLongValue(long value) {
      
      longValue_ = value;
    }
    /**
     * <code>optional int64 longValue = 2;</code>
     */
    private void clearLongValue() {
      
      longValue_ = 0L;
    }

    public static final int FLOATVALUE_FIELD_NUMBER = 3;
    private float floatValue_;
    /**
     * <code>optional float floatValue = 3;</code>
     */
    public float getFloatValue() {
      return floatValue_;
    }
    /**
     * <code>optional float floatValue = 3;</code>
     */
    private void setFloatValue(float value) {
      
      floatValue_ = value;
    }
    /**
     * <code>optional float floatValue = 3;</code>
     */
    private void clearFloatValue() {
      
      floatValue_ = 0F;
    }

    public static final int DOUBLEVALUE_FIELD_NUMBER = 4;
    private double doubleValue_;
    /**
     * <code>optional double doubleValue = 4;</code>
     */
    public double getDoubleValue() {
      return doubleValue_;
    }
    /**
     * <code>optional double doubleValue = 4;</code>
     */
    private void setDoubleValue(double value) {
      
      doubleValue_ = value;
    }
    /**
     * <code>optional double doubleValue = 4;</code>
     */
    private void clearDoubleValue() {
      
      doubleValue_ = 0D;
    }

    public static final int BOOLEANVALUE_FIELD_NUMBER = 5;
    private boolean booleanValue_;
    /**
     * <code>optional bool booleanValue = 5;</code>
     */
    public boolean getBooleanValue() {
      return booleanValue_;
    }
    /**
     * <code>optional bool booleanValue = 5;</code>
     */
    private void setBooleanValue(boolean value) {
      
      booleanValue_ = value;
    }
    /**
     * <code>optional bool booleanValue = 5;</code>
     */
    private void clearBooleanValue() {
      
      booleanValue_ = false;
    }

    public static final int STRINGVALUE_FIELD_NUMBER = 6;
    private java.lang.String stringValue_;
    /**
     * <code>optional string stringValue = 6;</code>
     */
    public java.lang.String getStringValue() {
      return stringValue_;
    }
    /**
     * <code>optional string stringValue = 6;</code>
     */
    public com.google.protobuf.ByteString
        getStringValueBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(stringValue_);
    }
    /**
     * <code>optional string stringValue = 6;</code>
     */
    private void setStringValue(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      stringValue_ = value;
    }
    /**
     * <code>optional string stringValue = 6;</code>
     */
    private void clearStringValue() {
      
      stringValue_ = getDefaultInstance().getStringValue();
    }
    /**
     * <code>optional string stringValue = 6;</code>
     */
    private void setStringValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      stringValue_ = value.toStringUtf8();
    }

    public static final int NESTEDVALUE_FIELD_NUMBER = 7;
    private net.badata.protobuf.converter.proto.MappingProto.NestedTest nestedValue_;
    /**
     * <code>optional .net.badata.protobuf.converter.proto.NestedTest nestedValue = 7;</code>
     */
    public boolean hasNestedValue() {
      return nestedValue_ != null;
    }
    /**
     * <code>optional .net.badata.protobuf.converter.proto.NestedTest nestedValue = 7;</code>
     */
    public net.badata.protobuf.converter.proto.MappingProto.NestedTest getNestedValue() {
      return nestedValue_ == null ? net.badata.protobuf.converter.proto.MappingProto.NestedTest.getDefaultInstance() : nestedValue_;
    }
    /**
     * <code>optional .net.badata.protobuf.converter.proto.NestedTest nestedValue = 7;</code>
     */
    private void setNestedValue(net.badata.protobuf.converter.proto.MappingProto.NestedTest value) {
      if (value == null) {
        throw new NullPointerException();
      }
      nestedValue_ = value;
      
      }
    /**
     * <code>optional .net.badata.protobuf.converter.proto.NestedTest nestedValue = 7;</code>
     */
    private void setNestedValue(
        net.badata.protobuf.converter.proto.MappingProto.NestedTest.Builder builderForValue) {
      nestedValue_ = builderForValue.build();
      
    }
    /**
     * <code>optional .net.badata.protobuf.converter.proto.NestedTest nestedValue = 7;</code>
     */
    private void mergeNestedValue(net.badata.protobuf.converter.proto.MappingProto.NestedTest value) {
      if (nestedValue_ != null &&
          nestedValue_ != net.badata.protobuf.converter.proto.MappingProto.NestedTest.getDefaultInstance()) {
        nestedValue_ =
          net.badata.protobuf.converter.proto.MappingProto.NestedTest.newBuilder(nestedValue_).mergeFrom(value).buildPartial();
      } else {
        nestedValue_ = value;
      }
      
    }
    /**
     * <code>optional .net.badata.protobuf.converter.proto.NestedTest nestedValue = 7;</code>
     */
    private void clearNestedValue() {  nestedValue_ = null;
      
    }

    public static final int STRINGLISTVALUE_FIELD_NUMBER = 8;
    private com.google.protobuf.Internal.ProtobufList<String> stringListValue_;
    /**
     * <code>repeated string stringListValue = 8;</code>
     */
    public java.util.List<String> getStringListValueList() {
      return stringListValue_;
    }
    /**
     * <code>repeated string stringListValue = 8;</code>
     */
    public int getStringListValueCount() {
      return stringListValue_.size();
    }
    /**
     * <code>repeated string stringListValue = 8;</code>
     */
    public java.lang.String getStringListValue(int index) {
      return stringListValue_.get(index);
    }
    /**
     * <code>repeated string stringListValue = 8;</code>
     */
    public com.google.protobuf.ByteString
        getStringListValueBytes(int index) {
      return com.google.protobuf.ByteString.copyFromUtf8(
          stringListValue_.get(index));
    }
    private void ensureStringListValueIsMutable() {
      if (!stringListValue_.isModifiable()) {
        stringListValue_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(stringListValue_);
       }
    }
    /**
     * <code>repeated string stringListValue = 8;</code>
     */
    private void setStringListValue(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureStringListValueIsMutable();
      stringListValue_.set(index, value);
    }
    /**
     * <code>repeated string stringListValue = 8;</code>
     */
    private void addStringListValue(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureStringListValueIsMutable();
      stringListValue_.add(value);
    }
    /**
     * <code>repeated string stringListValue = 8;</code>
     */
    private void addAllStringListValue(
        java.lang.Iterable<java.lang.String> values) {
      ensureStringListValueIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, stringListValue_);
    }
    /**
     * <code>repeated string stringListValue = 8;</code>
     */
    private void clearStringListValue() {
      stringListValue_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }
    /**
     * <code>repeated string stringListValue = 8;</code>
     */
    private void addStringListValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureStringListValueIsMutable();
      stringListValue_.add(value.toStringUtf8());
    }

    public static final int NESTEDLISTVALUE_FIELD_NUMBER = 9;
    private com.google.protobuf.Internal.ProtobufList<net.badata.protobuf.converter.proto.MappingProto.NestedTest> nestedListValue_;
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.NestedTest nestedListValue = 9;</code>
     */
    public java.util.List<net.badata.protobuf.converter.proto.MappingProto.NestedTest> getNestedListValueList() {
      return nestedListValue_;
    }
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.NestedTest nestedListValue = 9;</code>
     */
    public java.util.List<? extends net.badata.protobuf.converter.proto.MappingProto.NestedTestOrBuilder> 
        getNestedListValueOrBuilderList() {
      return nestedListValue_;
    }
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.NestedTest nestedListValue = 9;</code>
     */
    public int getNestedListValueCount() {
      return nestedListValue_.size();
    }
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.NestedTest nestedListValue = 9;</code>
     */
    public net.badata.protobuf.converter.proto.MappingProto.NestedTest getNestedListValue(int index) {
      return nestedListValue_.get(index);
    }
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.NestedTest nestedListValue = 9;</code>
     */
    public net.badata.protobuf.converter.proto.MappingProto.NestedTestOrBuilder getNestedListValueOrBuilder(
        int index) {
      return nestedListValue_.get(index);
    }
    private void ensureNestedListValueIsMutable() {
      if (!nestedListValue_.isModifiable()) {
        nestedListValue_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(nestedListValue_);
       }
    }

    /**
     * <code>repeated .net.badata.protobuf.converter.proto.NestedTest nestedListValue = 9;</code>
     */
    private void setNestedListValue(
        int index, net.badata.protobuf.converter.proto.MappingProto.NestedTest value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureNestedListValueIsMutable();
      nestedListValue_.set(index, value);
    }
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.NestedTest nestedListValue = 9;</code>
     */
    private void setNestedListValue(
        int index, net.badata.protobuf.converter.proto.MappingProto.NestedTest.Builder builderForValue) {
      ensureNestedListValueIsMutable();
      nestedListValue_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.NestedTest nestedListValue = 9;</code>
     */
    private void addNestedListValue(net.badata.protobuf.converter.proto.MappingProto.NestedTest value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureNestedListValueIsMutable();
      nestedListValue_.add(value);
    }
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.NestedTest nestedListValue = 9;</code>
     */
    private void addNestedListValue(
        int index, net.badata.protobuf.converter.proto.MappingProto.NestedTest value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureNestedListValueIsMutable();
      nestedListValue_.add(index, value);
    }
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.NestedTest nestedListValue = 9;</code>
     */
    private void addNestedListValue(
        net.badata.protobuf.converter.proto.MappingProto.NestedTest.Builder builderForValue) {
      ensureNestedListValueIsMutable();
      nestedListValue_.add(builderForValue.build());
    }
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.NestedTest nestedListValue = 9;</code>
     */
    private void addNestedListValue(
        int index, net.badata.protobuf.converter.proto.MappingProto.NestedTest.Builder builderForValue) {
      ensureNestedListValueIsMutable();
      nestedListValue_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.NestedTest nestedListValue = 9;</code>
     */
    private void addAllNestedListValue(
        java.lang.Iterable<? extends net.badata.protobuf.converter.proto.MappingProto.NestedTest> values) {
      ensureNestedListValueIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, nestedListValue_);
    }
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.NestedTest nestedListValue = 9;</code>
     */
    private void clearNestedListValue() {
      nestedListValue_ = emptyProtobufList();
    }
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.NestedTest nestedListValue = 9;</code>
     */
    private void removeNestedListValue(int index) {
      ensureNestedListValueIsMutable();
      nestedListValue_.remove(index);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (intValue_ != 0) {
        output.writeInt32(1, intValue_);
      }
      if (longValue_ != 0L) {
        output.writeInt64(2, longValue_);
      }
      if (floatValue_ != 0F) {
        output.writeFloat(3, floatValue_);
      }
      if (doubleValue_ != 0D) {
        output.writeDouble(4, doubleValue_);
      }
      if (booleanValue_ != false) {
        output.writeBool(5, booleanValue_);
      }
      if (!stringValue_.isEmpty()) {
        output.writeString(6, getStringValue());
      }
      if (nestedValue_ != null) {
        output.writeMessage(7, getNestedValue());
      }
      for (int i = 0; i < stringListValue_.size(); i++) {
        output.writeString(8, stringListValue_.get(i));
      }
      for (int i = 0; i < nestedListValue_.size(); i++) {
        output.writeMessage(9, nestedListValue_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (intValue_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, intValue_);
      }
      if (longValue_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, longValue_);
      }
      if (floatValue_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, floatValue_);
      }
      if (doubleValue_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, doubleValue_);
      }
      if (booleanValue_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, booleanValue_);
      }
      if (!stringValue_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getStringValue());
      }
      if (nestedValue_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getNestedValue());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < stringListValue_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeStringSizeNoTag(stringListValue_.get(i));
        }
        size += dataSize;
        size += 1 * getStringListValueList().size();
      }
      for (int i = 0; i < nestedListValue_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, nestedListValue_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static net.badata.protobuf.converter.proto.MappingProto.MappingTest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.badata.protobuf.converter.proto.MappingProto.MappingTest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.MappingProto.MappingTest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.badata.protobuf.converter.proto.MappingProto.MappingTest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.MappingProto.MappingTest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.badata.protobuf.converter.proto.MappingProto.MappingTest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.MappingProto.MappingTest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static net.badata.protobuf.converter.proto.MappingProto.MappingTest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.MappingProto.MappingTest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.badata.protobuf.converter.proto.MappingProto.MappingTest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.badata.protobuf.converter.proto.MappingProto.MappingTest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code net.badata.protobuf.converter.proto.MappingTest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          net.badata.protobuf.converter.proto.MappingProto.MappingTest, Builder> implements
        // @@protoc_insertion_point(builder_implements:net.badata.protobuf.converter.proto.MappingTest)
        net.badata.protobuf.converter.proto.MappingProto.MappingTestOrBuilder {
      // Construct using net.badata.protobuf.converter.proto.MappingProto.MappingTest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional int32 intValue = 1;</code>
       */
      public int getIntValue() {
        return instance.getIntValue();
      }
      /**
       * <code>optional int32 intValue = 1;</code>
       */
      public Builder setIntValue(int value) {
        copyOnWrite();
        instance.setIntValue(value);
        return this;
      }
      /**
       * <code>optional int32 intValue = 1;</code>
       */
      public Builder clearIntValue() {
        copyOnWrite();
        instance.clearIntValue();
        return this;
      }

      /**
       * <code>optional int64 longValue = 2;</code>
       */
      public long getLongValue() {
        return instance.getLongValue();
      }
      /**
       * <code>optional int64 longValue = 2;</code>
       */
      public Builder setLongValue(long value) {
        copyOnWrite();
        instance.setLongValue(value);
        return this;
      }
      /**
       * <code>optional int64 longValue = 2;</code>
       */
      public Builder clearLongValue() {
        copyOnWrite();
        instance.clearLongValue();
        return this;
      }

      /**
       * <code>optional float floatValue = 3;</code>
       */
      public float getFloatValue() {
        return instance.getFloatValue();
      }
      /**
       * <code>optional float floatValue = 3;</code>
       */
      public Builder setFloatValue(float value) {
        copyOnWrite();
        instance.setFloatValue(value);
        return this;
      }
      /**
       * <code>optional float floatValue = 3;</code>
       */
      public Builder clearFloatValue() {
        copyOnWrite();
        instance.clearFloatValue();
        return this;
      }

      /**
       * <code>optional double doubleValue = 4;</code>
       */
      public double getDoubleValue() {
        return instance.getDoubleValue();
      }
      /**
       * <code>optional double doubleValue = 4;</code>
       */
      public Builder setDoubleValue(double value) {
        copyOnWrite();
        instance.setDoubleValue(value);
        return this;
      }
      /**
       * <code>optional double doubleValue = 4;</code>
       */
      public Builder clearDoubleValue() {
        copyOnWrite();
        instance.clearDoubleValue();
        return this;
      }

      /**
       * <code>optional bool booleanValue = 5;</code>
       */
      public boolean getBooleanValue() {
        return instance.getBooleanValue();
      }
      /**
       * <code>optional bool booleanValue = 5;</code>
       */
      public Builder setBooleanValue(boolean value) {
        copyOnWrite();
        instance.setBooleanValue(value);
        return this;
      }
      /**
       * <code>optional bool booleanValue = 5;</code>
       */
      public Builder clearBooleanValue() {
        copyOnWrite();
        instance.clearBooleanValue();
        return this;
      }

      /**
       * <code>optional string stringValue = 6;</code>
       */
      public java.lang.String getStringValue() {
        return instance.getStringValue();
      }
      /**
       * <code>optional string stringValue = 6;</code>
       */
      public com.google.protobuf.ByteString
          getStringValueBytes() {
        return instance.getStringValueBytes();
      }
      /**
       * <code>optional string stringValue = 6;</code>
       */
      public Builder setStringValue(
          java.lang.String value) {
        copyOnWrite();
        instance.setStringValue(value);
        return this;
      }
      /**
       * <code>optional string stringValue = 6;</code>
       */
      public Builder clearStringValue() {
        copyOnWrite();
        instance.clearStringValue();
        return this;
      }
      /**
       * <code>optional string stringValue = 6;</code>
       */
      public Builder setStringValueBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setStringValueBytes(value);
        return this;
      }

      /**
       * <code>optional .net.badata.protobuf.converter.proto.NestedTest nestedValue = 7;</code>
       */
      public boolean hasNestedValue() {
        return instance.hasNestedValue();
      }
      /**
       * <code>optional .net.badata.protobuf.converter.proto.NestedTest nestedValue = 7;</code>
       */
      public net.badata.protobuf.converter.proto.MappingProto.NestedTest getNestedValue() {
        return instance.getNestedValue();
      }
      /**
       * <code>optional .net.badata.protobuf.converter.proto.NestedTest nestedValue = 7;</code>
       */
      public Builder setNestedValue(net.badata.protobuf.converter.proto.MappingProto.NestedTest value) {
        copyOnWrite();
        instance.setNestedValue(value);
        return this;
        }
      /**
       * <code>optional .net.badata.protobuf.converter.proto.NestedTest nestedValue = 7;</code>
       */
      public Builder setNestedValue(
          net.badata.protobuf.converter.proto.MappingProto.NestedTest.Builder builderForValue) {
        copyOnWrite();
        instance.setNestedValue(builderForValue);
        return this;
      }
      /**
       * <code>optional .net.badata.protobuf.converter.proto.NestedTest nestedValue = 7;</code>
       */
      public Builder mergeNestedValue(net.badata.protobuf.converter.proto.MappingProto.NestedTest value) {
        copyOnWrite();
        instance.mergeNestedValue(value);
        return this;
      }
      /**
       * <code>optional .net.badata.protobuf.converter.proto.NestedTest nestedValue = 7;</code>
       */
      public Builder clearNestedValue() {  copyOnWrite();
        instance.clearNestedValue();
        return this;
      }

      /**
       * <code>repeated string stringListValue = 8;</code>
       */
      public java.util.List<String>
          getStringListValueList() {
        return java.util.Collections.unmodifiableList(
            instance.getStringListValueList());
      }
      /**
       * <code>repeated string stringListValue = 8;</code>
       */
      public int getStringListValueCount() {
        return instance.getStringListValueCount();
      }
      /**
       * <code>repeated string stringListValue = 8;</code>
       */
      public java.lang.String getStringListValue(int index) {
        return instance.getStringListValue(index);
      }
      /**
       * <code>repeated string stringListValue = 8;</code>
       */
      public com.google.protobuf.ByteString
          getStringListValueBytes(int index) {
        return instance.getStringListValueBytes(index);
      }
      /**
       * <code>repeated string stringListValue = 8;</code>
       */
      public Builder setStringListValue(
          int index, java.lang.String value) {
        copyOnWrite();
        instance.setStringListValue(index, value);
        return this;
      }
      /**
       * <code>repeated string stringListValue = 8;</code>
       */
      public Builder addStringListValue(
          java.lang.String value) {
        copyOnWrite();
        instance.addStringListValue(value);
        return this;
      }
      /**
       * <code>repeated string stringListValue = 8;</code>
       */
      public Builder addAllStringListValue(
          java.lang.Iterable<java.lang.String> values) {
        copyOnWrite();
        instance.addAllStringListValue(values);
        return this;
      }
      /**
       * <code>repeated string stringListValue = 8;</code>
       */
      public Builder clearStringListValue() {
        copyOnWrite();
        instance.clearStringListValue();
        return this;
      }
      /**
       * <code>repeated string stringListValue = 8;</code>
       */
      public Builder addStringListValueBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.addStringListValueBytes(value);
        return this;
      }

      /**
       * <code>repeated .net.badata.protobuf.converter.proto.NestedTest nestedListValue = 9;</code>
       */
      public java.util.List<net.badata.protobuf.converter.proto.MappingProto.NestedTest> getNestedListValueList() {
        return java.util.Collections.unmodifiableList(
            instance.getNestedListValueList());
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.NestedTest nestedListValue = 9;</code>
       */
      public int getNestedListValueCount() {
        return instance.getNestedListValueCount();
      }/**
       * <code>repeated .net.badata.protobuf.converter.proto.NestedTest nestedListValue = 9;</code>
       */
      public net.badata.protobuf.converter.proto.MappingProto.NestedTest getNestedListValue(int index) {
        return instance.getNestedListValue(index);
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.NestedTest nestedListValue = 9;</code>
       */
      public Builder setNestedListValue(
          int index, net.badata.protobuf.converter.proto.MappingProto.NestedTest value) {
        copyOnWrite();
        instance.setNestedListValue(index, value);
        return this;
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.NestedTest nestedListValue = 9;</code>
       */
      public Builder setNestedListValue(
          int index, net.badata.protobuf.converter.proto.MappingProto.NestedTest.Builder builderForValue) {
        copyOnWrite();
        instance.setNestedListValue(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.NestedTest nestedListValue = 9;</code>
       */
      public Builder addNestedListValue(net.badata.protobuf.converter.proto.MappingProto.NestedTest value) {
        copyOnWrite();
        instance.addNestedListValue(value);
        return this;
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.NestedTest nestedListValue = 9;</code>
       */
      public Builder addNestedListValue(
          int index, net.badata.protobuf.converter.proto.MappingProto.NestedTest value) {
        copyOnWrite();
        instance.addNestedListValue(index, value);
        return this;
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.NestedTest nestedListValue = 9;</code>
       */
      public Builder addNestedListValue(
          net.badata.protobuf.converter.proto.MappingProto.NestedTest.Builder builderForValue) {
        copyOnWrite();
        instance.addNestedListValue(builderForValue);
        return this;
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.NestedTest nestedListValue = 9;</code>
       */
      public Builder addNestedListValue(
          int index, net.badata.protobuf.converter.proto.MappingProto.NestedTest.Builder builderForValue) {
        copyOnWrite();
        instance.addNestedListValue(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.NestedTest nestedListValue = 9;</code>
       */
      public Builder addAllNestedListValue(
          java.lang.Iterable<? extends net.badata.protobuf.converter.proto.MappingProto.NestedTest> values) {
        copyOnWrite();
        instance.addAllNestedListValue(values);
        return this;
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.NestedTest nestedListValue = 9;</code>
       */
      public Builder clearNestedListValue() {
        copyOnWrite();
        instance.clearNestedListValue();
        return this;
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.NestedTest nestedListValue = 9;</code>
       */
      public Builder removeNestedListValue(int index) {
        copyOnWrite();
        instance.removeNestedListValue(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:net.badata.protobuf.converter.proto.MappingTest)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new net.badata.protobuf.converter.proto.MappingProto.MappingTest();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          stringListValue_.makeImmutable();
          nestedListValue_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          net.badata.protobuf.converter.proto.MappingProto.MappingTest other = (net.badata.protobuf.converter.proto.MappingProto.MappingTest) arg1;
          intValue_ = visitor.visitInt(intValue_ != 0, intValue_,
              other.intValue_ != 0, other.intValue_);
          longValue_ = visitor.visitLong(longValue_ != 0L, longValue_,
              other.longValue_ != 0L, other.longValue_);
          floatValue_ = visitor.visitFloat(floatValue_ != 0F, floatValue_,
              other.floatValue_ != 0F, other.floatValue_);
          doubleValue_ = visitor.visitDouble(doubleValue_ != 0D, doubleValue_,
              other.doubleValue_ != 0D, other.doubleValue_);
          booleanValue_ = visitor.visitBoolean(booleanValue_ != false, booleanValue_,
              other.booleanValue_ != false, other.booleanValue_);
          stringValue_ = visitor.visitString(!stringValue_.isEmpty(), stringValue_,
              !other.stringValue_.isEmpty(), other.stringValue_);
          nestedValue_ = visitor.visitMessage(nestedValue_, other.nestedValue_);
          stringListValue_= visitor.visitList(stringListValue_, other.stringListValue_);
          nestedListValue_= visitor.visitList(nestedListValue_, other.nestedListValue_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {

                  intValue_ = input.readInt32();
                  break;
                }
                case 16: {

                  longValue_ = input.readInt64();
                  break;
                }
                case 29: {

                  floatValue_ = input.readFloat();
                  break;
                }
                case 33: {

                  doubleValue_ = input.readDouble();
                  break;
                }
                case 40: {

                  booleanValue_ = input.readBool();
                  break;
                }
                case 50: {
                  String s = input.readStringRequireUtf8();

                  stringValue_ = s;
                  break;
                }
                case 58: {
                  net.badata.protobuf.converter.proto.MappingProto.NestedTest.Builder subBuilder = null;
                  if (nestedValue_ != null) {
                    subBuilder = nestedValue_.toBuilder();
                  }
                  nestedValue_ = input.readMessage(net.badata.protobuf.converter.proto.MappingProto.NestedTest.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom(nestedValue_);
                    nestedValue_ = subBuilder.buildPartial();
                  }

                  break;
                }
                case 66: {
                  String s = input.readStringRequireUtf8();
                  if (!stringListValue_.isModifiable()) {
                    stringListValue_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(stringListValue_);
                  }
                  stringListValue_.add(s);
                  break;
                }
                case 74: {
                  if (!nestedListValue_.isModifiable()) {
                    nestedListValue_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(nestedListValue_);
                  }
                  nestedListValue_.add(
                      input.readMessage(net.badata.protobuf.converter.proto.MappingProto.NestedTest.parser(), extensionRegistry));
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (net.badata.protobuf.converter.proto.MappingProto.MappingTest.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:net.badata.protobuf.converter.proto.MappingTest)
    private static final net.badata.protobuf.converter.proto.MappingProto.MappingTest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MappingTest();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static net.badata.protobuf.converter.proto.MappingProto.MappingTest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<MappingTest> PARSER;

    public static com.google.protobuf.Parser<MappingTest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
