// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: multi_mapping_test.proto

package net.badata.protobuf.converter.proto;

public final class MultiMappingProto {
  private MultiMappingProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface MultiMappingFirstOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.badata.protobuf.converter.proto.MultiMappingFirst)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional int32 intValue = 1;</code>
     */
    int getIntValue();

    /**
     * <code>optional int64 longValue = 2;</code>
     */
    long getLongValue();
  }
  /**
   * Protobuf type {@code net.badata.protobuf.converter.proto.MultiMappingFirst}
   */
  public  static final class MultiMappingFirst extends
      com.google.protobuf.GeneratedMessageLite<
          MultiMappingFirst, MultiMappingFirst.Builder> implements
      // @@protoc_insertion_point(message_implements:net.badata.protobuf.converter.proto.MultiMappingFirst)
      MultiMappingFirstOrBuilder {
    private MultiMappingFirst() {
    }
    public static final int INTVALUE_FIELD_NUMBER = 1;
    private int intValue_;
    /**
     * <code>optional int32 intValue = 1;</code>
     */
    public int getIntValue() {
      return intValue_;
    }
    /**
     * <code>optional int32 intValue = 1;</code>
     */
    private void setIntValue(int value) {
      
      intValue_ = value;
    }
    /**
     * <code>optional int32 intValue = 1;</code>
     */
    private void clearIntValue() {
      
      intValue_ = 0;
    }

    public static final int LONGVALUE_FIELD_NUMBER = 2;
    private long longValue_;
    /**
     * <code>optional int64 longValue = 2;</code>
     */
    public long getLongValue() {
      return longValue_;
    }
    /**
     * <code>optional int64 longValue = 2;</code>
     */
    private void setLongValue(long value) {
      
      longValue_ = value;
    }
    /**
     * <code>optional int64 longValue = 2;</code>
     */
    private void clearLongValue() {
      
      longValue_ = 0L;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (intValue_ != 0) {
        output.writeInt32(1, intValue_);
      }
      if (longValue_ != 0L) {
        output.writeInt64(2, longValue_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (intValue_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, intValue_);
      }
      if (longValue_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, longValue_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code net.badata.protobuf.converter.proto.MultiMappingFirst}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst, Builder> implements
        // @@protoc_insertion_point(builder_implements:net.badata.protobuf.converter.proto.MultiMappingFirst)
        net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirstOrBuilder {
      // Construct using net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional int32 intValue = 1;</code>
       */
      public int getIntValue() {
        return instance.getIntValue();
      }
      /**
       * <code>optional int32 intValue = 1;</code>
       */
      public Builder setIntValue(int value) {
        copyOnWrite();
        instance.setIntValue(value);
        return this;
      }
      /**
       * <code>optional int32 intValue = 1;</code>
       */
      public Builder clearIntValue() {
        copyOnWrite();
        instance.clearIntValue();
        return this;
      }

      /**
       * <code>optional int64 longValue = 2;</code>
       */
      public long getLongValue() {
        return instance.getLongValue();
      }
      /**
       * <code>optional int64 longValue = 2;</code>
       */
      public Builder setLongValue(long value) {
        copyOnWrite();
        instance.setLongValue(value);
        return this;
      }
      /**
       * <code>optional int64 longValue = 2;</code>
       */
      public Builder clearLongValue() {
        copyOnWrite();
        instance.clearLongValue();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:net.badata.protobuf.converter.proto.MultiMappingFirst)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst other = (net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst) arg1;
          intValue_ = visitor.visitInt(intValue_ != 0, intValue_,
              other.intValue_ != 0, other.intValue_);
          longValue_ = visitor.visitLong(longValue_ != 0L, longValue_,
              other.longValue_ != 0L, other.longValue_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {

                  intValue_ = input.readInt32();
                  break;
                }
                case 16: {

                  longValue_ = input.readInt64();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:net.badata.protobuf.converter.proto.MultiMappingFirst)
    private static final net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MultiMappingFirst();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<MultiMappingFirst> PARSER;

    public static com.google.protobuf.Parser<MultiMappingFirst> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface MultiMappingSecondOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.badata.protobuf.converter.proto.MultiMappingSecond)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional int32 intValue = 1;</code>
     */
    int getIntValue();

    /**
     * <code>optional int64 longValueChanged = 2;</code>
     */
    long getLongValueChanged();

    /**
     * <code>optional string unusableValue = 3;</code>
     */
    java.lang.String getUnusableValue();
    /**
     * <code>optional string unusableValue = 3;</code>
     */
    com.google.protobuf.ByteString
        getUnusableValueBytes();
  }
  /**
   * Protobuf type {@code net.badata.protobuf.converter.proto.MultiMappingSecond}
   */
  public  static final class MultiMappingSecond extends
      com.google.protobuf.GeneratedMessageLite<
          MultiMappingSecond, MultiMappingSecond.Builder> implements
      // @@protoc_insertion_point(message_implements:net.badata.protobuf.converter.proto.MultiMappingSecond)
      MultiMappingSecondOrBuilder {
    private MultiMappingSecond() {
      unusableValue_ = "";
    }
    public static final int INTVALUE_FIELD_NUMBER = 1;
    private int intValue_;
    /**
     * <code>optional int32 intValue = 1;</code>
     */
    public int getIntValue() {
      return intValue_;
    }
    /**
     * <code>optional int32 intValue = 1;</code>
     */
    private void setIntValue(int value) {
      
      intValue_ = value;
    }
    /**
     * <code>optional int32 intValue = 1;</code>
     */
    private void clearIntValue() {
      
      intValue_ = 0;
    }

    public static final int LONGVALUECHANGED_FIELD_NUMBER = 2;
    private long longValueChanged_;
    /**
     * <code>optional int64 longValueChanged = 2;</code>
     */
    public long getLongValueChanged() {
      return longValueChanged_;
    }
    /**
     * <code>optional int64 longValueChanged = 2;</code>
     */
    private void setLongValueChanged(long value) {
      
      longValueChanged_ = value;
    }
    /**
     * <code>optional int64 longValueChanged = 2;</code>
     */
    private void clearLongValueChanged() {
      
      longValueChanged_ = 0L;
    }

    public static final int UNUSABLEVALUE_FIELD_NUMBER = 3;
    private java.lang.String unusableValue_;
    /**
     * <code>optional string unusableValue = 3;</code>
     */
    public java.lang.String getUnusableValue() {
      return unusableValue_;
    }
    /**
     * <code>optional string unusableValue = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUnusableValueBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(unusableValue_);
    }
    /**
     * <code>optional string unusableValue = 3;</code>
     */
    private void setUnusableValue(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      unusableValue_ = value;
    }
    /**
     * <code>optional string unusableValue = 3;</code>
     */
    private void clearUnusableValue() {
      
      unusableValue_ = getDefaultInstance().getUnusableValue();
    }
    /**
     * <code>optional string unusableValue = 3;</code>
     */
    private void setUnusableValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      unusableValue_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (intValue_ != 0) {
        output.writeInt32(1, intValue_);
      }
      if (longValueChanged_ != 0L) {
        output.writeInt64(2, longValueChanged_);
      }
      if (!unusableValue_.isEmpty()) {
        output.writeString(3, getUnusableValue());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (intValue_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, intValue_);
      }
      if (longValueChanged_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, longValueChanged_);
      }
      if (!unusableValue_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getUnusableValue());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code net.badata.protobuf.converter.proto.MultiMappingSecond}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond, Builder> implements
        // @@protoc_insertion_point(builder_implements:net.badata.protobuf.converter.proto.MultiMappingSecond)
        net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecondOrBuilder {
      // Construct using net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional int32 intValue = 1;</code>
       */
      public int getIntValue() {
        return instance.getIntValue();
      }
      /**
       * <code>optional int32 intValue = 1;</code>
       */
      public Builder setIntValue(int value) {
        copyOnWrite();
        instance.setIntValue(value);
        return this;
      }
      /**
       * <code>optional int32 intValue = 1;</code>
       */
      public Builder clearIntValue() {
        copyOnWrite();
        instance.clearIntValue();
        return this;
      }

      /**
       * <code>optional int64 longValueChanged = 2;</code>
       */
      public long getLongValueChanged() {
        return instance.getLongValueChanged();
      }
      /**
       * <code>optional int64 longValueChanged = 2;</code>
       */
      public Builder setLongValueChanged(long value) {
        copyOnWrite();
        instance.setLongValueChanged(value);
        return this;
      }
      /**
       * <code>optional int64 longValueChanged = 2;</code>
       */
      public Builder clearLongValueChanged() {
        copyOnWrite();
        instance.clearLongValueChanged();
        return this;
      }

      /**
       * <code>optional string unusableValue = 3;</code>
       */
      public java.lang.String getUnusableValue() {
        return instance.getUnusableValue();
      }
      /**
       * <code>optional string unusableValue = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUnusableValueBytes() {
        return instance.getUnusableValueBytes();
      }
      /**
       * <code>optional string unusableValue = 3;</code>
       */
      public Builder setUnusableValue(
          java.lang.String value) {
        copyOnWrite();
        instance.setUnusableValue(value);
        return this;
      }
      /**
       * <code>optional string unusableValue = 3;</code>
       */
      public Builder clearUnusableValue() {
        copyOnWrite();
        instance.clearUnusableValue();
        return this;
      }
      /**
       * <code>optional string unusableValue = 3;</code>
       */
      public Builder setUnusableValueBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUnusableValueBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:net.badata.protobuf.converter.proto.MultiMappingSecond)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond other = (net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond) arg1;
          intValue_ = visitor.visitInt(intValue_ != 0, intValue_,
              other.intValue_ != 0, other.intValue_);
          longValueChanged_ = visitor.visitLong(longValueChanged_ != 0L, longValueChanged_,
              other.longValueChanged_ != 0L, other.longValueChanged_);
          unusableValue_ = visitor.visitString(!unusableValue_.isEmpty(), unusableValue_,
              !other.unusableValue_.isEmpty(), other.unusableValue_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {

                  intValue_ = input.readInt32();
                  break;
                }
                case 16: {

                  longValueChanged_ = input.readInt64();
                  break;
                }
                case 26: {
                  String s = input.readStringRequireUtf8();

                  unusableValue_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:net.badata.protobuf.converter.proto.MultiMappingSecond)
    private static final net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MultiMappingSecond();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<MultiMappingSecond> PARSER;

    public static com.google.protobuf.Parser<MultiMappingSecond> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface MultiMappingTestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.badata.protobuf.converter.proto.MultiMappingTest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional .net.badata.protobuf.converter.proto.MultiMappingFirst multiMappingValue = 1;</code>
     */
    boolean hasMultiMappingValue();
    /**
     * <code>optional .net.badata.protobuf.converter.proto.MultiMappingFirst multiMappingValue = 1;</code>
     */
    net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst getMultiMappingValue();

    /**
     * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
     */
    java.util.List<net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond> 
        getMultiMappingListValueList();
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
     */
    net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond getMultiMappingListValue(int index);
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
     */
    int getMultiMappingListValueCount();
  }
  /**
   * Protobuf type {@code net.badata.protobuf.converter.proto.MultiMappingTest}
   */
  public  static final class MultiMappingTest extends
      com.google.protobuf.GeneratedMessageLite<
          MultiMappingTest, MultiMappingTest.Builder> implements
      // @@protoc_insertion_point(message_implements:net.badata.protobuf.converter.proto.MultiMappingTest)
      MultiMappingTestOrBuilder {
    private MultiMappingTest() {
      multiMappingListValue_ = emptyProtobufList();
    }
    private int bitField0_;
    public static final int MULTIMAPPINGVALUE_FIELD_NUMBER = 1;
    private net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst multiMappingValue_;
    /**
     * <code>optional .net.badata.protobuf.converter.proto.MultiMappingFirst multiMappingValue = 1;</code>
     */
    public boolean hasMultiMappingValue() {
      return multiMappingValue_ != null;
    }
    /**
     * <code>optional .net.badata.protobuf.converter.proto.MultiMappingFirst multiMappingValue = 1;</code>
     */
    public net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst getMultiMappingValue() {
      return multiMappingValue_ == null ? net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst.getDefaultInstance() : multiMappingValue_;
    }
    /**
     * <code>optional .net.badata.protobuf.converter.proto.MultiMappingFirst multiMappingValue = 1;</code>
     */
    private void setMultiMappingValue(net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst value) {
      if (value == null) {
        throw new NullPointerException();
      }
      multiMappingValue_ = value;
      
      }
    /**
     * <code>optional .net.badata.protobuf.converter.proto.MultiMappingFirst multiMappingValue = 1;</code>
     */
    private void setMultiMappingValue(
        net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst.Builder builderForValue) {
      multiMappingValue_ = builderForValue.build();
      
    }
    /**
     * <code>optional .net.badata.protobuf.converter.proto.MultiMappingFirst multiMappingValue = 1;</code>
     */
    private void mergeMultiMappingValue(net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst value) {
      if (multiMappingValue_ != null &&
          multiMappingValue_ != net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst.getDefaultInstance()) {
        multiMappingValue_ =
          net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst.newBuilder(multiMappingValue_).mergeFrom(value).buildPartial();
      } else {
        multiMappingValue_ = value;
      }
      
    }
    /**
     * <code>optional .net.badata.protobuf.converter.proto.MultiMappingFirst multiMappingValue = 1;</code>
     */
    private void clearMultiMappingValue() {  multiMappingValue_ = null;
      
    }

    public static final int MULTIMAPPINGLISTVALUE_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.ProtobufList<net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond> multiMappingListValue_;
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
     */
    public java.util.List<net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond> getMultiMappingListValueList() {
      return multiMappingListValue_;
    }
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
     */
    public java.util.List<? extends net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecondOrBuilder> 
        getMultiMappingListValueOrBuilderList() {
      return multiMappingListValue_;
    }
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
     */
    public int getMultiMappingListValueCount() {
      return multiMappingListValue_.size();
    }
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
     */
    public net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond getMultiMappingListValue(int index) {
      return multiMappingListValue_.get(index);
    }
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
     */
    public net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecondOrBuilder getMultiMappingListValueOrBuilder(
        int index) {
      return multiMappingListValue_.get(index);
    }
    private void ensureMultiMappingListValueIsMutable() {
      if (!multiMappingListValue_.isModifiable()) {
        multiMappingListValue_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(multiMappingListValue_);
       }
    }

    /**
     * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
     */
    private void setMultiMappingListValue(
        int index, net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureMultiMappingListValueIsMutable();
      multiMappingListValue_.set(index, value);
    }
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
     */
    private void setMultiMappingListValue(
        int index, net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond.Builder builderForValue) {
      ensureMultiMappingListValueIsMutable();
      multiMappingListValue_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
     */
    private void addMultiMappingListValue(net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureMultiMappingListValueIsMutable();
      multiMappingListValue_.add(value);
    }
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
     */
    private void addMultiMappingListValue(
        int index, net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureMultiMappingListValueIsMutable();
      multiMappingListValue_.add(index, value);
    }
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
     */
    private void addMultiMappingListValue(
        net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond.Builder builderForValue) {
      ensureMultiMappingListValueIsMutable();
      multiMappingListValue_.add(builderForValue.build());
    }
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
     */
    private void addMultiMappingListValue(
        int index, net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond.Builder builderForValue) {
      ensureMultiMappingListValueIsMutable();
      multiMappingListValue_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
     */
    private void addAllMultiMappingListValue(
        java.lang.Iterable<? extends net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond> values) {
      ensureMultiMappingListValueIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, multiMappingListValue_);
    }
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
     */
    private void clearMultiMappingListValue() {
      multiMappingListValue_ = emptyProtobufList();
    }
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
     */
    private void removeMultiMappingListValue(int index) {
      ensureMultiMappingListValueIsMutable();
      multiMappingListValue_.remove(index);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (multiMappingValue_ != null) {
        output.writeMessage(1, getMultiMappingValue());
      }
      for (int i = 0; i < multiMappingListValue_.size(); i++) {
        output.writeMessage(2, multiMappingListValue_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (multiMappingValue_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMultiMappingValue());
      }
      for (int i = 0; i < multiMappingListValue_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, multiMappingListValue_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code net.badata.protobuf.converter.proto.MultiMappingTest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest, Builder> implements
        // @@protoc_insertion_point(builder_implements:net.badata.protobuf.converter.proto.MultiMappingTest)
        net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTestOrBuilder {
      // Construct using net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional .net.badata.protobuf.converter.proto.MultiMappingFirst multiMappingValue = 1;</code>
       */
      public boolean hasMultiMappingValue() {
        return instance.hasMultiMappingValue();
      }
      /**
       * <code>optional .net.badata.protobuf.converter.proto.MultiMappingFirst multiMappingValue = 1;</code>
       */
      public net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst getMultiMappingValue() {
        return instance.getMultiMappingValue();
      }
      /**
       * <code>optional .net.badata.protobuf.converter.proto.MultiMappingFirst multiMappingValue = 1;</code>
       */
      public Builder setMultiMappingValue(net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst value) {
        copyOnWrite();
        instance.setMultiMappingValue(value);
        return this;
        }
      /**
       * <code>optional .net.badata.protobuf.converter.proto.MultiMappingFirst multiMappingValue = 1;</code>
       */
      public Builder setMultiMappingValue(
          net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst.Builder builderForValue) {
        copyOnWrite();
        instance.setMultiMappingValue(builderForValue);
        return this;
      }
      /**
       * <code>optional .net.badata.protobuf.converter.proto.MultiMappingFirst multiMappingValue = 1;</code>
       */
      public Builder mergeMultiMappingValue(net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst value) {
        copyOnWrite();
        instance.mergeMultiMappingValue(value);
        return this;
      }
      /**
       * <code>optional .net.badata.protobuf.converter.proto.MultiMappingFirst multiMappingValue = 1;</code>
       */
      public Builder clearMultiMappingValue() {  copyOnWrite();
        instance.clearMultiMappingValue();
        return this;
      }

      /**
       * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
       */
      public java.util.List<net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond> getMultiMappingListValueList() {
        return java.util.Collections.unmodifiableList(
            instance.getMultiMappingListValueList());
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
       */
      public int getMultiMappingListValueCount() {
        return instance.getMultiMappingListValueCount();
      }/**
       * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
       */
      public net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond getMultiMappingListValue(int index) {
        return instance.getMultiMappingListValue(index);
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
       */
      public Builder setMultiMappingListValue(
          int index, net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond value) {
        copyOnWrite();
        instance.setMultiMappingListValue(index, value);
        return this;
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
       */
      public Builder setMultiMappingListValue(
          int index, net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond.Builder builderForValue) {
        copyOnWrite();
        instance.setMultiMappingListValue(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
       */
      public Builder addMultiMappingListValue(net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond value) {
        copyOnWrite();
        instance.addMultiMappingListValue(value);
        return this;
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
       */
      public Builder addMultiMappingListValue(
          int index, net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond value) {
        copyOnWrite();
        instance.addMultiMappingListValue(index, value);
        return this;
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
       */
      public Builder addMultiMappingListValue(
          net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond.Builder builderForValue) {
        copyOnWrite();
        instance.addMultiMappingListValue(builderForValue);
        return this;
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
       */
      public Builder addMultiMappingListValue(
          int index, net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond.Builder builderForValue) {
        copyOnWrite();
        instance.addMultiMappingListValue(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
       */
      public Builder addAllMultiMappingListValue(
          java.lang.Iterable<? extends net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond> values) {
        copyOnWrite();
        instance.addAllMultiMappingListValue(values);
        return this;
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
       */
      public Builder clearMultiMappingListValue() {
        copyOnWrite();
        instance.clearMultiMappingListValue();
        return this;
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
       */
      public Builder removeMultiMappingListValue(int index) {
        copyOnWrite();
        instance.removeMultiMappingListValue(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:net.badata.protobuf.converter.proto.MultiMappingTest)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          multiMappingListValue_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest other = (net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest) arg1;
          multiMappingValue_ = visitor.visitMessage(multiMappingValue_, other.multiMappingValue_);
          multiMappingListValue_= visitor.visitList(multiMappingListValue_, other.multiMappingListValue_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst.Builder subBuilder = null;
                  if (multiMappingValue_ != null) {
                    subBuilder = multiMappingValue_.toBuilder();
                  }
                  multiMappingValue_ = input.readMessage(net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom(multiMappingValue_);
                    multiMappingValue_ = subBuilder.buildPartial();
                  }

                  break;
                }
                case 18: {
                  if (!multiMappingListValue_.isModifiable()) {
                    multiMappingListValue_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(multiMappingListValue_);
                  }
                  multiMappingListValue_.add(
                      input.readMessage(net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond.parser(), extensionRegistry));
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:net.badata.protobuf.converter.proto.MultiMappingTest)
    private static final net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MultiMappingTest();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<MultiMappingTest> PARSER;

    public static com.google.protobuf.Parser<MultiMappingTest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
