// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto2_test.proto

package net.badata.protobuf.converter.proto;

public final class Proto2Proto {
  private Proto2Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface Proto2NestedTestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.badata.protobuf.converter.proto.Proto2NestedTest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string stringValue = 1;</code>
     */
    boolean hasStringValue();
    /**
     * <code>optional string stringValue = 1;</code>
     */
    java.lang.String getStringValue();
    /**
     * <code>optional string stringValue = 1;</code>
     */
    com.google.protobuf.ByteString
        getStringValueBytes();
  }
  /**
   * Protobuf type {@code net.badata.protobuf.converter.proto.Proto2NestedTest}
   */
  public  static final class Proto2NestedTest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:net.badata.protobuf.converter.proto.Proto2NestedTest)
      Proto2NestedTestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Proto2NestedTest.newBuilder() to construct.
    private Proto2NestedTest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Proto2NestedTest() {
      stringValue_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Proto2NestedTest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              stringValue_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.badata.protobuf.converter.proto.Proto2Proto.internal_static_net_badata_protobuf_converter_proto_Proto2NestedTest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.badata.protobuf.converter.proto.Proto2Proto.internal_static_net_badata_protobuf_converter_proto_Proto2NestedTest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest.class, net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest.Builder.class);
    }

    private int bitField0_;
    public static final int STRINGVALUE_FIELD_NUMBER = 1;
    private volatile java.lang.Object stringValue_;
    /**
     * <code>optional string stringValue = 1;</code>
     */
    public boolean hasStringValue() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string stringValue = 1;</code>
     */
    public java.lang.String getStringValue() {
      java.lang.Object ref = stringValue_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          stringValue_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string stringValue = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStringValueBytes() {
      java.lang.Object ref = stringValue_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stringValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, stringValue_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, stringValue_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest)) {
        return super.equals(obj);
      }
      net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest other = (net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest) obj;

      boolean result = true;
      result = result && (hasStringValue() == other.hasStringValue());
      if (hasStringValue()) {
        result = result && getStringValue()
            .equals(other.getStringValue());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasStringValue()) {
        hash = (37 * hash) + STRINGVALUE_FIELD_NUMBER;
        hash = (53 * hash) + getStringValue().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.badata.protobuf.converter.proto.Proto2NestedTest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:net.badata.protobuf.converter.proto.Proto2NestedTest)
        net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.badata.protobuf.converter.proto.Proto2Proto.internal_static_net_badata_protobuf_converter_proto_Proto2NestedTest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.badata.protobuf.converter.proto.Proto2Proto.internal_static_net_badata_protobuf_converter_proto_Proto2NestedTest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest.class, net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest.Builder.class);
      }

      // Construct using net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        stringValue_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.badata.protobuf.converter.proto.Proto2Proto.internal_static_net_badata_protobuf_converter_proto_Proto2NestedTest_descriptor;
      }

      public net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest getDefaultInstanceForType() {
        return net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest.getDefaultInstance();
      }

      public net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest build() {
        net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest buildPartial() {
        net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest result = new net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.stringValue_ = stringValue_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest) {
          return mergeFrom((net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest other) {
        if (other == net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest.getDefaultInstance()) return this;
        if (other.hasStringValue()) {
          bitField0_ |= 0x00000001;
          stringValue_ = other.stringValue_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object stringValue_ = "";
      /**
       * <code>optional string stringValue = 1;</code>
       */
      public boolean hasStringValue() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string stringValue = 1;</code>
       */
      public java.lang.String getStringValue() {
        java.lang.Object ref = stringValue_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            stringValue_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string stringValue = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStringValueBytes() {
        java.lang.Object ref = stringValue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stringValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string stringValue = 1;</code>
       */
      public Builder setStringValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        stringValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string stringValue = 1;</code>
       */
      public Builder clearStringValue() {
        bitField0_ = (bitField0_ & ~0x00000001);
        stringValue_ = getDefaultInstance().getStringValue();
        onChanged();
        return this;
      }
      /**
       * <code>optional string stringValue = 1;</code>
       */
      public Builder setStringValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        stringValue_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:net.badata.protobuf.converter.proto.Proto2NestedTest)
    }

    // @@protoc_insertion_point(class_scope:net.badata.protobuf.converter.proto.Proto2NestedTest)
    private static final net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest();
    }

    public static net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Proto2NestedTest>
        PARSER = new com.google.protobuf.AbstractParser<Proto2NestedTest>() {
      public Proto2NestedTest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Proto2NestedTest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Proto2NestedTest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Proto2NestedTest> getParserForType() {
      return PARSER;
    }

    public net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Proto2MappingTestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.badata.protobuf.converter.proto.Proto2MappingTest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 intValue = 1;</code>
     */
    boolean hasIntValue();
    /**
     * <code>optional int32 intValue = 1;</code>
     */
    int getIntValue();

    /**
     * <code>optional int64 longValue = 2;</code>
     */
    boolean hasLongValue();
    /**
     * <code>optional int64 longValue = 2;</code>
     */
    long getLongValue();

    /**
     * <code>optional float floatValue = 3;</code>
     */
    boolean hasFloatValue();
    /**
     * <code>optional float floatValue = 3;</code>
     */
    float getFloatValue();

    /**
     * <code>optional double doubleValue = 4;</code>
     */
    boolean hasDoubleValue();
    /**
     * <code>optional double doubleValue = 4;</code>
     */
    double getDoubleValue();

    /**
     * <code>optional bool booleanValue = 5;</code>
     */
    boolean hasBooleanValue();
    /**
     * <code>optional bool booleanValue = 5;</code>
     */
    boolean getBooleanValue();

    /**
     * <code>optional string stringValue = 6;</code>
     */
    boolean hasStringValue();
    /**
     * <code>optional string stringValue = 6;</code>
     */
    java.lang.String getStringValue();
    /**
     * <code>optional string stringValue = 6;</code>
     */
    com.google.protobuf.ByteString
        getStringValueBytes();

    /**
     * <code>optional .net.badata.protobuf.converter.proto.Proto2NestedTest nestedValue = 7;</code>
     */
    boolean hasNestedValue();
    /**
     * <code>optional .net.badata.protobuf.converter.proto.Proto2NestedTest nestedValue = 7;</code>
     */
    net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest getNestedValue();
    /**
     * <code>optional .net.badata.protobuf.converter.proto.Proto2NestedTest nestedValue = 7;</code>
     */
    net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTestOrBuilder getNestedValueOrBuilder();

    /**
     * <code>repeated string stringListValue = 8;</code>
     */
    java.util.List<java.lang.String>
        getStringListValueList();
    /**
     * <code>repeated string stringListValue = 8;</code>
     */
    int getStringListValueCount();
    /**
     * <code>repeated string stringListValue = 8;</code>
     */
    java.lang.String getStringListValue(int index);
    /**
     * <code>repeated string stringListValue = 8;</code>
     */
    com.google.protobuf.ByteString
        getStringListValueBytes(int index);

    /**
     * <code>repeated .net.badata.protobuf.converter.proto.Proto2NestedTest nestedListValue = 9;</code>
     */
    java.util.List<net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest> 
        getNestedListValueList();
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.Proto2NestedTest nestedListValue = 9;</code>
     */
    net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest getNestedListValue(int index);
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.Proto2NestedTest nestedListValue = 9;</code>
     */
    int getNestedListValueCount();
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.Proto2NestedTest nestedListValue = 9;</code>
     */
    java.util.List<? extends net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTestOrBuilder> 
        getNestedListValueOrBuilderList();
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.Proto2NestedTest nestedListValue = 9;</code>
     */
    net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTestOrBuilder getNestedListValueOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code net.badata.protobuf.converter.proto.Proto2MappingTest}
   */
  public  static final class Proto2MappingTest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:net.badata.protobuf.converter.proto.Proto2MappingTest)
      Proto2MappingTestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Proto2MappingTest.newBuilder() to construct.
    private Proto2MappingTest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Proto2MappingTest() {
      intValue_ = 0;
      longValue_ = 0L;
      floatValue_ = 0F;
      doubleValue_ = 0D;
      booleanValue_ = false;
      stringValue_ = "";
      stringListValue_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      nestedListValue_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Proto2MappingTest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              intValue_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              longValue_ = input.readInt64();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              floatValue_ = input.readFloat();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              doubleValue_ = input.readDouble();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              booleanValue_ = input.readBool();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              stringValue_ = bs;
              break;
            }
            case 58: {
              net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest.Builder subBuilder = null;
              if (((bitField0_ & 0x00000040) == 0x00000040)) {
                subBuilder = nestedValue_.toBuilder();
              }
              nestedValue_ = input.readMessage(net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(nestedValue_);
                nestedValue_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000040;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
                stringListValue_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000080;
              }
              stringListValue_.add(bs);
              break;
            }
            case 74: {
              if (!((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
                nestedListValue_ = new java.util.ArrayList<net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest>();
                mutable_bitField0_ |= 0x00000100;
              }
              nestedListValue_.add(
                  input.readMessage(net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
          stringListValue_ = stringListValue_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
          nestedListValue_ = java.util.Collections.unmodifiableList(nestedListValue_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.badata.protobuf.converter.proto.Proto2Proto.internal_static_net_badata_protobuf_converter_proto_Proto2MappingTest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.badata.protobuf.converter.proto.Proto2Proto.internal_static_net_badata_protobuf_converter_proto_Proto2MappingTest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.badata.protobuf.converter.proto.Proto2Proto.Proto2MappingTest.class, net.badata.protobuf.converter.proto.Proto2Proto.Proto2MappingTest.Builder.class);
    }

    private int bitField0_;
    public static final int INTVALUE_FIELD_NUMBER = 1;
    private int intValue_;
    /**
     * <code>optional int32 intValue = 1;</code>
     */
    public boolean hasIntValue() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 intValue = 1;</code>
     */
    public int getIntValue() {
      return intValue_;
    }

    public static final int LONGVALUE_FIELD_NUMBER = 2;
    private long longValue_;
    /**
     * <code>optional int64 longValue = 2;</code>
     */
    public boolean hasLongValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 longValue = 2;</code>
     */
    public long getLongValue() {
      return longValue_;
    }

    public static final int FLOATVALUE_FIELD_NUMBER = 3;
    private float floatValue_;
    /**
     * <code>optional float floatValue = 3;</code>
     */
    public boolean hasFloatValue() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional float floatValue = 3;</code>
     */
    public float getFloatValue() {
      return floatValue_;
    }

    public static final int DOUBLEVALUE_FIELD_NUMBER = 4;
    private double doubleValue_;
    /**
     * <code>optional double doubleValue = 4;</code>
     */
    public boolean hasDoubleValue() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional double doubleValue = 4;</code>
     */
    public double getDoubleValue() {
      return doubleValue_;
    }

    public static final int BOOLEANVALUE_FIELD_NUMBER = 5;
    private boolean booleanValue_;
    /**
     * <code>optional bool booleanValue = 5;</code>
     */
    public boolean hasBooleanValue() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bool booleanValue = 5;</code>
     */
    public boolean getBooleanValue() {
      return booleanValue_;
    }

    public static final int STRINGVALUE_FIELD_NUMBER = 6;
    private volatile java.lang.Object stringValue_;
    /**
     * <code>optional string stringValue = 6;</code>
     */
    public boolean hasStringValue() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string stringValue = 6;</code>
     */
    public java.lang.String getStringValue() {
      java.lang.Object ref = stringValue_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          stringValue_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string stringValue = 6;</code>
     */
    public com.google.protobuf.ByteString
        getStringValueBytes() {
      java.lang.Object ref = stringValue_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stringValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NESTEDVALUE_FIELD_NUMBER = 7;
    private net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest nestedValue_;
    /**
     * <code>optional .net.badata.protobuf.converter.proto.Proto2NestedTest nestedValue = 7;</code>
     */
    public boolean hasNestedValue() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional .net.badata.protobuf.converter.proto.Proto2NestedTest nestedValue = 7;</code>
     */
    public net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest getNestedValue() {
      return nestedValue_ == null ? net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest.getDefaultInstance() : nestedValue_;
    }
    /**
     * <code>optional .net.badata.protobuf.converter.proto.Proto2NestedTest nestedValue = 7;</code>
     */
    public net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTestOrBuilder getNestedValueOrBuilder() {
      return nestedValue_ == null ? net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest.getDefaultInstance() : nestedValue_;
    }

    public static final int STRINGLISTVALUE_FIELD_NUMBER = 8;
    private com.google.protobuf.LazyStringList stringListValue_;
    /**
     * <code>repeated string stringListValue = 8;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getStringListValueList() {
      return stringListValue_;
    }
    /**
     * <code>repeated string stringListValue = 8;</code>
     */
    public int getStringListValueCount() {
      return stringListValue_.size();
    }
    /**
     * <code>repeated string stringListValue = 8;</code>
     */
    public java.lang.String getStringListValue(int index) {
      return stringListValue_.get(index);
    }
    /**
     * <code>repeated string stringListValue = 8;</code>
     */
    public com.google.protobuf.ByteString
        getStringListValueBytes(int index) {
      return stringListValue_.getByteString(index);
    }

    public static final int NESTEDLISTVALUE_FIELD_NUMBER = 9;
    private java.util.List<net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest> nestedListValue_;
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.Proto2NestedTest nestedListValue = 9;</code>
     */
    public java.util.List<net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest> getNestedListValueList() {
      return nestedListValue_;
    }
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.Proto2NestedTest nestedListValue = 9;</code>
     */
    public java.util.List<? extends net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTestOrBuilder> 
        getNestedListValueOrBuilderList() {
      return nestedListValue_;
    }
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.Proto2NestedTest nestedListValue = 9;</code>
     */
    public int getNestedListValueCount() {
      return nestedListValue_.size();
    }
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.Proto2NestedTest nestedListValue = 9;</code>
     */
    public net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest getNestedListValue(int index) {
      return nestedListValue_.get(index);
    }
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.Proto2NestedTest nestedListValue = 9;</code>
     */
    public net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTestOrBuilder getNestedListValueOrBuilder(
        int index) {
      return nestedListValue_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, intValue_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, longValue_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, floatValue_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, doubleValue_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, booleanValue_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, stringValue_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeMessage(7, getNestedValue());
      }
      for (int i = 0; i < stringListValue_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, stringListValue_.getRaw(i));
      }
      for (int i = 0; i < nestedListValue_.size(); i++) {
        output.writeMessage(9, nestedListValue_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, intValue_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, longValue_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, floatValue_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, doubleValue_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, booleanValue_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, stringValue_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getNestedValue());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < stringListValue_.size(); i++) {
          dataSize += computeStringSizeNoTag(stringListValue_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getStringListValueList().size();
      }
      for (int i = 0; i < nestedListValue_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, nestedListValue_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.badata.protobuf.converter.proto.Proto2Proto.Proto2MappingTest)) {
        return super.equals(obj);
      }
      net.badata.protobuf.converter.proto.Proto2Proto.Proto2MappingTest other = (net.badata.protobuf.converter.proto.Proto2Proto.Proto2MappingTest) obj;

      boolean result = true;
      result = result && (hasIntValue() == other.hasIntValue());
      if (hasIntValue()) {
        result = result && (getIntValue()
            == other.getIntValue());
      }
      result = result && (hasLongValue() == other.hasLongValue());
      if (hasLongValue()) {
        result = result && (getLongValue()
            == other.getLongValue());
      }
      result = result && (hasFloatValue() == other.hasFloatValue());
      if (hasFloatValue()) {
        result = result && (
            java.lang.Float.floatToIntBits(getFloatValue())
            == java.lang.Float.floatToIntBits(
                other.getFloatValue()));
      }
      result = result && (hasDoubleValue() == other.hasDoubleValue());
      if (hasDoubleValue()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getDoubleValue())
            == java.lang.Double.doubleToLongBits(
                other.getDoubleValue()));
      }
      result = result && (hasBooleanValue() == other.hasBooleanValue());
      if (hasBooleanValue()) {
        result = result && (getBooleanValue()
            == other.getBooleanValue());
      }
      result = result && (hasStringValue() == other.hasStringValue());
      if (hasStringValue()) {
        result = result && getStringValue()
            .equals(other.getStringValue());
      }
      result = result && (hasNestedValue() == other.hasNestedValue());
      if (hasNestedValue()) {
        result = result && getNestedValue()
            .equals(other.getNestedValue());
      }
      result = result && getStringListValueList()
          .equals(other.getStringListValueList());
      result = result && getNestedListValueList()
          .equals(other.getNestedListValueList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasIntValue()) {
        hash = (37 * hash) + INTVALUE_FIELD_NUMBER;
        hash = (53 * hash) + getIntValue();
      }
      if (hasLongValue()) {
        hash = (37 * hash) + LONGVALUE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getLongValue());
      }
      if (hasFloatValue()) {
        hash = (37 * hash) + FLOATVALUE_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getFloatValue());
      }
      if (hasDoubleValue()) {
        hash = (37 * hash) + DOUBLEVALUE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getDoubleValue()));
      }
      if (hasBooleanValue()) {
        hash = (37 * hash) + BOOLEANVALUE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getBooleanValue());
      }
      if (hasStringValue()) {
        hash = (37 * hash) + STRINGVALUE_FIELD_NUMBER;
        hash = (53 * hash) + getStringValue().hashCode();
      }
      if (hasNestedValue()) {
        hash = (37 * hash) + NESTEDVALUE_FIELD_NUMBER;
        hash = (53 * hash) + getNestedValue().hashCode();
      }
      if (getStringListValueCount() > 0) {
        hash = (37 * hash) + STRINGLISTVALUE_FIELD_NUMBER;
        hash = (53 * hash) + getStringListValueList().hashCode();
      }
      if (getNestedListValueCount() > 0) {
        hash = (37 * hash) + NESTEDLISTVALUE_FIELD_NUMBER;
        hash = (53 * hash) + getNestedListValueList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.badata.protobuf.converter.proto.Proto2Proto.Proto2MappingTest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.badata.protobuf.converter.proto.Proto2Proto.Proto2MappingTest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.Proto2Proto.Proto2MappingTest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.badata.protobuf.converter.proto.Proto2Proto.Proto2MappingTest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.Proto2Proto.Proto2MappingTest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.badata.protobuf.converter.proto.Proto2Proto.Proto2MappingTest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.Proto2Proto.Proto2MappingTest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.badata.protobuf.converter.proto.Proto2Proto.Proto2MappingTest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.Proto2Proto.Proto2MappingTest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.badata.protobuf.converter.proto.Proto2Proto.Proto2MappingTest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.Proto2Proto.Proto2MappingTest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.badata.protobuf.converter.proto.Proto2Proto.Proto2MappingTest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.badata.protobuf.converter.proto.Proto2Proto.Proto2MappingTest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.badata.protobuf.converter.proto.Proto2MappingTest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:net.badata.protobuf.converter.proto.Proto2MappingTest)
        net.badata.protobuf.converter.proto.Proto2Proto.Proto2MappingTestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.badata.protobuf.converter.proto.Proto2Proto.internal_static_net_badata_protobuf_converter_proto_Proto2MappingTest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.badata.protobuf.converter.proto.Proto2Proto.internal_static_net_badata_protobuf_converter_proto_Proto2MappingTest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.badata.protobuf.converter.proto.Proto2Proto.Proto2MappingTest.class, net.badata.protobuf.converter.proto.Proto2Proto.Proto2MappingTest.Builder.class);
      }

      // Construct using net.badata.protobuf.converter.proto.Proto2Proto.Proto2MappingTest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getNestedValueFieldBuilder();
          getNestedListValueFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        intValue_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        longValue_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        floatValue_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        doubleValue_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        booleanValue_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        stringValue_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        if (nestedValueBuilder_ == null) {
          nestedValue_ = null;
        } else {
          nestedValueBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        stringListValue_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        if (nestedListValueBuilder_ == null) {
          nestedListValue_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000100);
        } else {
          nestedListValueBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.badata.protobuf.converter.proto.Proto2Proto.internal_static_net_badata_protobuf_converter_proto_Proto2MappingTest_descriptor;
      }

      public net.badata.protobuf.converter.proto.Proto2Proto.Proto2MappingTest getDefaultInstanceForType() {
        return net.badata.protobuf.converter.proto.Proto2Proto.Proto2MappingTest.getDefaultInstance();
      }

      public net.badata.protobuf.converter.proto.Proto2Proto.Proto2MappingTest build() {
        net.badata.protobuf.converter.proto.Proto2Proto.Proto2MappingTest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.badata.protobuf.converter.proto.Proto2Proto.Proto2MappingTest buildPartial() {
        net.badata.protobuf.converter.proto.Proto2Proto.Proto2MappingTest result = new net.badata.protobuf.converter.proto.Proto2Proto.Proto2MappingTest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.intValue_ = intValue_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.longValue_ = longValue_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.floatValue_ = floatValue_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.doubleValue_ = doubleValue_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.booleanValue_ = booleanValue_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.stringValue_ = stringValue_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        if (nestedValueBuilder_ == null) {
          result.nestedValue_ = nestedValue_;
        } else {
          result.nestedValue_ = nestedValueBuilder_.build();
        }
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          stringListValue_ = stringListValue_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.stringListValue_ = stringListValue_;
        if (nestedListValueBuilder_ == null) {
          if (((bitField0_ & 0x00000100) == 0x00000100)) {
            nestedListValue_ = java.util.Collections.unmodifiableList(nestedListValue_);
            bitField0_ = (bitField0_ & ~0x00000100);
          }
          result.nestedListValue_ = nestedListValue_;
        } else {
          result.nestedListValue_ = nestedListValueBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.badata.protobuf.converter.proto.Proto2Proto.Proto2MappingTest) {
          return mergeFrom((net.badata.protobuf.converter.proto.Proto2Proto.Proto2MappingTest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.badata.protobuf.converter.proto.Proto2Proto.Proto2MappingTest other) {
        if (other == net.badata.protobuf.converter.proto.Proto2Proto.Proto2MappingTest.getDefaultInstance()) return this;
        if (other.hasIntValue()) {
          setIntValue(other.getIntValue());
        }
        if (other.hasLongValue()) {
          setLongValue(other.getLongValue());
        }
        if (other.hasFloatValue()) {
          setFloatValue(other.getFloatValue());
        }
        if (other.hasDoubleValue()) {
          setDoubleValue(other.getDoubleValue());
        }
        if (other.hasBooleanValue()) {
          setBooleanValue(other.getBooleanValue());
        }
        if (other.hasStringValue()) {
          bitField0_ |= 0x00000020;
          stringValue_ = other.stringValue_;
          onChanged();
        }
        if (other.hasNestedValue()) {
          mergeNestedValue(other.getNestedValue());
        }
        if (!other.stringListValue_.isEmpty()) {
          if (stringListValue_.isEmpty()) {
            stringListValue_ = other.stringListValue_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureStringListValueIsMutable();
            stringListValue_.addAll(other.stringListValue_);
          }
          onChanged();
        }
        if (nestedListValueBuilder_ == null) {
          if (!other.nestedListValue_.isEmpty()) {
            if (nestedListValue_.isEmpty()) {
              nestedListValue_ = other.nestedListValue_;
              bitField0_ = (bitField0_ & ~0x00000100);
            } else {
              ensureNestedListValueIsMutable();
              nestedListValue_.addAll(other.nestedListValue_);
            }
            onChanged();
          }
        } else {
          if (!other.nestedListValue_.isEmpty()) {
            if (nestedListValueBuilder_.isEmpty()) {
              nestedListValueBuilder_.dispose();
              nestedListValueBuilder_ = null;
              nestedListValue_ = other.nestedListValue_;
              bitField0_ = (bitField0_ & ~0x00000100);
              nestedListValueBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getNestedListValueFieldBuilder() : null;
            } else {
              nestedListValueBuilder_.addAllMessages(other.nestedListValue_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.badata.protobuf.converter.proto.Proto2Proto.Proto2MappingTest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.badata.protobuf.converter.proto.Proto2Proto.Proto2MappingTest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int intValue_ ;
      /**
       * <code>optional int32 intValue = 1;</code>
       */
      public boolean hasIntValue() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 intValue = 1;</code>
       */
      public int getIntValue() {
        return intValue_;
      }
      /**
       * <code>optional int32 intValue = 1;</code>
       */
      public Builder setIntValue(int value) {
        bitField0_ |= 0x00000001;
        intValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 intValue = 1;</code>
       */
      public Builder clearIntValue() {
        bitField0_ = (bitField0_ & ~0x00000001);
        intValue_ = 0;
        onChanged();
        return this;
      }

      private long longValue_ ;
      /**
       * <code>optional int64 longValue = 2;</code>
       */
      public boolean hasLongValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 longValue = 2;</code>
       */
      public long getLongValue() {
        return longValue_;
      }
      /**
       * <code>optional int64 longValue = 2;</code>
       */
      public Builder setLongValue(long value) {
        bitField0_ |= 0x00000002;
        longValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 longValue = 2;</code>
       */
      public Builder clearLongValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        longValue_ = 0L;
        onChanged();
        return this;
      }

      private float floatValue_ ;
      /**
       * <code>optional float floatValue = 3;</code>
       */
      public boolean hasFloatValue() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional float floatValue = 3;</code>
       */
      public float getFloatValue() {
        return floatValue_;
      }
      /**
       * <code>optional float floatValue = 3;</code>
       */
      public Builder setFloatValue(float value) {
        bitField0_ |= 0x00000004;
        floatValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float floatValue = 3;</code>
       */
      public Builder clearFloatValue() {
        bitField0_ = (bitField0_ & ~0x00000004);
        floatValue_ = 0F;
        onChanged();
        return this;
      }

      private double doubleValue_ ;
      /**
       * <code>optional double doubleValue = 4;</code>
       */
      public boolean hasDoubleValue() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional double doubleValue = 4;</code>
       */
      public double getDoubleValue() {
        return doubleValue_;
      }
      /**
       * <code>optional double doubleValue = 4;</code>
       */
      public Builder setDoubleValue(double value) {
        bitField0_ |= 0x00000008;
        doubleValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double doubleValue = 4;</code>
       */
      public Builder clearDoubleValue() {
        bitField0_ = (bitField0_ & ~0x00000008);
        doubleValue_ = 0D;
        onChanged();
        return this;
      }

      private boolean booleanValue_ ;
      /**
       * <code>optional bool booleanValue = 5;</code>
       */
      public boolean hasBooleanValue() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bool booleanValue = 5;</code>
       */
      public boolean getBooleanValue() {
        return booleanValue_;
      }
      /**
       * <code>optional bool booleanValue = 5;</code>
       */
      public Builder setBooleanValue(boolean value) {
        bitField0_ |= 0x00000010;
        booleanValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool booleanValue = 5;</code>
       */
      public Builder clearBooleanValue() {
        bitField0_ = (bitField0_ & ~0x00000010);
        booleanValue_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object stringValue_ = "";
      /**
       * <code>optional string stringValue = 6;</code>
       */
      public boolean hasStringValue() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string stringValue = 6;</code>
       */
      public java.lang.String getStringValue() {
        java.lang.Object ref = stringValue_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            stringValue_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string stringValue = 6;</code>
       */
      public com.google.protobuf.ByteString
          getStringValueBytes() {
        java.lang.Object ref = stringValue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stringValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string stringValue = 6;</code>
       */
      public Builder setStringValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        stringValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string stringValue = 6;</code>
       */
      public Builder clearStringValue() {
        bitField0_ = (bitField0_ & ~0x00000020);
        stringValue_ = getDefaultInstance().getStringValue();
        onChanged();
        return this;
      }
      /**
       * <code>optional string stringValue = 6;</code>
       */
      public Builder setStringValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        stringValue_ = value;
        onChanged();
        return this;
      }

      private net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest nestedValue_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest, net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest.Builder, net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTestOrBuilder> nestedValueBuilder_;
      /**
       * <code>optional .net.badata.protobuf.converter.proto.Proto2NestedTest nestedValue = 7;</code>
       */
      public boolean hasNestedValue() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional .net.badata.protobuf.converter.proto.Proto2NestedTest nestedValue = 7;</code>
       */
      public net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest getNestedValue() {
        if (nestedValueBuilder_ == null) {
          return nestedValue_ == null ? net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest.getDefaultInstance() : nestedValue_;
        } else {
          return nestedValueBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .net.badata.protobuf.converter.proto.Proto2NestedTest nestedValue = 7;</code>
       */
      public Builder setNestedValue(net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest value) {
        if (nestedValueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          nestedValue_ = value;
          onChanged();
        } else {
          nestedValueBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .net.badata.protobuf.converter.proto.Proto2NestedTest nestedValue = 7;</code>
       */
      public Builder setNestedValue(
          net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest.Builder builderForValue) {
        if (nestedValueBuilder_ == null) {
          nestedValue_ = builderForValue.build();
          onChanged();
        } else {
          nestedValueBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .net.badata.protobuf.converter.proto.Proto2NestedTest nestedValue = 7;</code>
       */
      public Builder mergeNestedValue(net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest value) {
        if (nestedValueBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040) &&
              nestedValue_ != null &&
              nestedValue_ != net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest.getDefaultInstance()) {
            nestedValue_ =
              net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest.newBuilder(nestedValue_).mergeFrom(value).buildPartial();
          } else {
            nestedValue_ = value;
          }
          onChanged();
        } else {
          nestedValueBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .net.badata.protobuf.converter.proto.Proto2NestedTest nestedValue = 7;</code>
       */
      public Builder clearNestedValue() {
        if (nestedValueBuilder_ == null) {
          nestedValue_ = null;
          onChanged();
        } else {
          nestedValueBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      /**
       * <code>optional .net.badata.protobuf.converter.proto.Proto2NestedTest nestedValue = 7;</code>
       */
      public net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest.Builder getNestedValueBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getNestedValueFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .net.badata.protobuf.converter.proto.Proto2NestedTest nestedValue = 7;</code>
       */
      public net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTestOrBuilder getNestedValueOrBuilder() {
        if (nestedValueBuilder_ != null) {
          return nestedValueBuilder_.getMessageOrBuilder();
        } else {
          return nestedValue_ == null ?
              net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest.getDefaultInstance() : nestedValue_;
        }
      }
      /**
       * <code>optional .net.badata.protobuf.converter.proto.Proto2NestedTest nestedValue = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest, net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest.Builder, net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTestOrBuilder> 
          getNestedValueFieldBuilder() {
        if (nestedValueBuilder_ == null) {
          nestedValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest, net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest.Builder, net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTestOrBuilder>(
                  getNestedValue(),
                  getParentForChildren(),
                  isClean());
          nestedValue_ = null;
        }
        return nestedValueBuilder_;
      }

      private com.google.protobuf.LazyStringList stringListValue_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureStringListValueIsMutable() {
        if (!((bitField0_ & 0x00000080) == 0x00000080)) {
          stringListValue_ = new com.google.protobuf.LazyStringArrayList(stringListValue_);
          bitField0_ |= 0x00000080;
         }
      }
      /**
       * <code>repeated string stringListValue = 8;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getStringListValueList() {
        return stringListValue_.getUnmodifiableView();
      }
      /**
       * <code>repeated string stringListValue = 8;</code>
       */
      public int getStringListValueCount() {
        return stringListValue_.size();
      }
      /**
       * <code>repeated string stringListValue = 8;</code>
       */
      public java.lang.String getStringListValue(int index) {
        return stringListValue_.get(index);
      }
      /**
       * <code>repeated string stringListValue = 8;</code>
       */
      public com.google.protobuf.ByteString
          getStringListValueBytes(int index) {
        return stringListValue_.getByteString(index);
      }
      /**
       * <code>repeated string stringListValue = 8;</code>
       */
      public Builder setStringListValue(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStringListValueIsMutable();
        stringListValue_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string stringListValue = 8;</code>
       */
      public Builder addStringListValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStringListValueIsMutable();
        stringListValue_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string stringListValue = 8;</code>
       */
      public Builder addAllStringListValue(
          java.lang.Iterable<java.lang.String> values) {
        ensureStringListValueIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, stringListValue_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string stringListValue = 8;</code>
       */
      public Builder clearStringListValue() {
        stringListValue_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string stringListValue = 8;</code>
       */
      public Builder addStringListValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStringListValueIsMutable();
        stringListValue_.add(value);
        onChanged();
        return this;
      }

      private java.util.List<net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest> nestedListValue_ =
        java.util.Collections.emptyList();
      private void ensureNestedListValueIsMutable() {
        if (!((bitField0_ & 0x00000100) == 0x00000100)) {
          nestedListValue_ = new java.util.ArrayList<net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest>(nestedListValue_);
          bitField0_ |= 0x00000100;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest, net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest.Builder, net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTestOrBuilder> nestedListValueBuilder_;

      /**
       * <code>repeated .net.badata.protobuf.converter.proto.Proto2NestedTest nestedListValue = 9;</code>
       */
      public java.util.List<net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest> getNestedListValueList() {
        if (nestedListValueBuilder_ == null) {
          return java.util.Collections.unmodifiableList(nestedListValue_);
        } else {
          return nestedListValueBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.Proto2NestedTest nestedListValue = 9;</code>
       */
      public int getNestedListValueCount() {
        if (nestedListValueBuilder_ == null) {
          return nestedListValue_.size();
        } else {
          return nestedListValueBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.Proto2NestedTest nestedListValue = 9;</code>
       */
      public net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest getNestedListValue(int index) {
        if (nestedListValueBuilder_ == null) {
          return nestedListValue_.get(index);
        } else {
          return nestedListValueBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.Proto2NestedTest nestedListValue = 9;</code>
       */
      public Builder setNestedListValue(
          int index, net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest value) {
        if (nestedListValueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNestedListValueIsMutable();
          nestedListValue_.set(index, value);
          onChanged();
        } else {
          nestedListValueBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.Proto2NestedTest nestedListValue = 9;</code>
       */
      public Builder setNestedListValue(
          int index, net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest.Builder builderForValue) {
        if (nestedListValueBuilder_ == null) {
          ensureNestedListValueIsMutable();
          nestedListValue_.set(index, builderForValue.build());
          onChanged();
        } else {
          nestedListValueBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.Proto2NestedTest nestedListValue = 9;</code>
       */
      public Builder addNestedListValue(net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest value) {
        if (nestedListValueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNestedListValueIsMutable();
          nestedListValue_.add(value);
          onChanged();
        } else {
          nestedListValueBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.Proto2NestedTest nestedListValue = 9;</code>
       */
      public Builder addNestedListValue(
          int index, net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest value) {
        if (nestedListValueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNestedListValueIsMutable();
          nestedListValue_.add(index, value);
          onChanged();
        } else {
          nestedListValueBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.Proto2NestedTest nestedListValue = 9;</code>
       */
      public Builder addNestedListValue(
          net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest.Builder builderForValue) {
        if (nestedListValueBuilder_ == null) {
          ensureNestedListValueIsMutable();
          nestedListValue_.add(builderForValue.build());
          onChanged();
        } else {
          nestedListValueBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.Proto2NestedTest nestedListValue = 9;</code>
       */
      public Builder addNestedListValue(
          int index, net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest.Builder builderForValue) {
        if (nestedListValueBuilder_ == null) {
          ensureNestedListValueIsMutable();
          nestedListValue_.add(index, builderForValue.build());
          onChanged();
        } else {
          nestedListValueBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.Proto2NestedTest nestedListValue = 9;</code>
       */
      public Builder addAllNestedListValue(
          java.lang.Iterable<? extends net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest> values) {
        if (nestedListValueBuilder_ == null) {
          ensureNestedListValueIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, nestedListValue_);
          onChanged();
        } else {
          nestedListValueBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.Proto2NestedTest nestedListValue = 9;</code>
       */
      public Builder clearNestedListValue() {
        if (nestedListValueBuilder_ == null) {
          nestedListValue_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000100);
          onChanged();
        } else {
          nestedListValueBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.Proto2NestedTest nestedListValue = 9;</code>
       */
      public Builder removeNestedListValue(int index) {
        if (nestedListValueBuilder_ == null) {
          ensureNestedListValueIsMutable();
          nestedListValue_.remove(index);
          onChanged();
        } else {
          nestedListValueBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.Proto2NestedTest nestedListValue = 9;</code>
       */
      public net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest.Builder getNestedListValueBuilder(
          int index) {
        return getNestedListValueFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.Proto2NestedTest nestedListValue = 9;</code>
       */
      public net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTestOrBuilder getNestedListValueOrBuilder(
          int index) {
        if (nestedListValueBuilder_ == null) {
          return nestedListValue_.get(index);  } else {
          return nestedListValueBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.Proto2NestedTest nestedListValue = 9;</code>
       */
      public java.util.List<? extends net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTestOrBuilder> 
           getNestedListValueOrBuilderList() {
        if (nestedListValueBuilder_ != null) {
          return nestedListValueBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(nestedListValue_);
        }
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.Proto2NestedTest nestedListValue = 9;</code>
       */
      public net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest.Builder addNestedListValueBuilder() {
        return getNestedListValueFieldBuilder().addBuilder(
            net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest.getDefaultInstance());
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.Proto2NestedTest nestedListValue = 9;</code>
       */
      public net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest.Builder addNestedListValueBuilder(
          int index) {
        return getNestedListValueFieldBuilder().addBuilder(
            index, net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest.getDefaultInstance());
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.Proto2NestedTest nestedListValue = 9;</code>
       */
      public java.util.List<net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest.Builder> 
           getNestedListValueBuilderList() {
        return getNestedListValueFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest, net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest.Builder, net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTestOrBuilder> 
          getNestedListValueFieldBuilder() {
        if (nestedListValueBuilder_ == null) {
          nestedListValueBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest, net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTest.Builder, net.badata.protobuf.converter.proto.Proto2Proto.Proto2NestedTestOrBuilder>(
                  nestedListValue_,
                  ((bitField0_ & 0x00000100) == 0x00000100),
                  getParentForChildren(),
                  isClean());
          nestedListValue_ = null;
        }
        return nestedListValueBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:net.badata.protobuf.converter.proto.Proto2MappingTest)
    }

    // @@protoc_insertion_point(class_scope:net.badata.protobuf.converter.proto.Proto2MappingTest)
    private static final net.badata.protobuf.converter.proto.Proto2Proto.Proto2MappingTest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.badata.protobuf.converter.proto.Proto2Proto.Proto2MappingTest();
    }

    public static net.badata.protobuf.converter.proto.Proto2Proto.Proto2MappingTest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Proto2MappingTest>
        PARSER = new com.google.protobuf.AbstractParser<Proto2MappingTest>() {
      public Proto2MappingTest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Proto2MappingTest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Proto2MappingTest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Proto2MappingTest> getParserForType() {
      return PARSER;
    }

    public net.badata.protobuf.converter.proto.Proto2Proto.Proto2MappingTest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_badata_protobuf_converter_proto_Proto2NestedTest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_badata_protobuf_converter_proto_Proto2NestedTest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_badata_protobuf_converter_proto_Proto2MappingTest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_badata_protobuf_converter_proto_Proto2MappingTest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021proto2_test.proto\022#net.badata.protobuf" +
      ".converter.proto\"\'\n\020Proto2NestedTest\022\023\n\013" +
      "stringValue\030\001 \001(\t\"\301\002\n\021Proto2MappingTest\022" +
      "\020\n\010intValue\030\001 \001(\005\022\021\n\tlongValue\030\002 \001(\003\022\022\n\n" +
      "floatValue\030\003 \001(\002\022\023\n\013doubleValue\030\004 \001(\001\022\024\n" +
      "\014booleanValue\030\005 \001(\010\022\023\n\013stringValue\030\006 \001(\t" +
      "\022J\n\013nestedValue\030\007 \001(\01325.net.badata.proto" +
      "buf.converter.proto.Proto2NestedTest\022\027\n\017" +
      "stringListValue\030\010 \003(\t\022N\n\017nestedListValue" +
      "\030\t \003(\01325.net.badata.protobuf.converter.p" +
      "roto.Proto2NestedTestB2\n#net.badata.prot" +
      "obuf.converter.protoB\013Proto2Proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_net_badata_protobuf_converter_proto_Proto2NestedTest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_net_badata_protobuf_converter_proto_Proto2NestedTest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_badata_protobuf_converter_proto_Proto2NestedTest_descriptor,
        new java.lang.String[] { "StringValue", });
    internal_static_net_badata_protobuf_converter_proto_Proto2MappingTest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_net_badata_protobuf_converter_proto_Proto2MappingTest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_badata_protobuf_converter_proto_Proto2MappingTest_descriptor,
        new java.lang.String[] { "IntValue", "LongValue", "FloatValue", "DoubleValue", "BooleanValue", "StringValue", "NestedValue", "StringListValue", "NestedListValue", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
