// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: field_resolver_test.proto

package net.badata.protobuf.converter.proto;

public final class ResolverProto {
  private ResolverProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ResolverTestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.badata.protobuf.converter.proto.ResolverTest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated string stringListValue = 1;</code>
     */
    java.util.List<String>
        getStringListValueList();
    /**
     * <code>repeated string stringListValue = 1;</code>
     */
    int getStringListValueCount();
    /**
     * <code>repeated string stringListValue = 1;</code>
     */
    java.lang.String getStringListValue(int index);
    /**
     * <code>repeated string stringListValue = 1;</code>
     */
    com.google.protobuf.ByteString
        getStringListValueBytes(int index);

    /**
     * <code>optional string delimitedStringValue = 3;</code>
     */
    java.lang.String getDelimitedStringValue();
    /**
     * <code>optional string delimitedStringValue = 3;</code>
     */
    com.google.protobuf.ByteString
        getDelimitedStringValueBytes();
  }
  /**
   * Protobuf type {@code net.badata.protobuf.converter.proto.ResolverTest}
   */
  public  static final class ResolverTest extends
      com.google.protobuf.GeneratedMessageLite<
          ResolverTest, ResolverTest.Builder> implements
      // @@protoc_insertion_point(message_implements:net.badata.protobuf.converter.proto.ResolverTest)
      ResolverTestOrBuilder {
    private ResolverTest() {
      stringListValue_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
      delimitedStringValue_ = "";
    }
    private int bitField0_;
    public static final int STRINGLISTVALUE_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<String> stringListValue_;
    /**
     * <code>repeated string stringListValue = 1;</code>
     */
    public java.util.List<String> getStringListValueList() {
      return stringListValue_;
    }
    /**
     * <code>repeated string stringListValue = 1;</code>
     */
    public int getStringListValueCount() {
      return stringListValue_.size();
    }
    /**
     * <code>repeated string stringListValue = 1;</code>
     */
    public java.lang.String getStringListValue(int index) {
      return stringListValue_.get(index);
    }
    /**
     * <code>repeated string stringListValue = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStringListValueBytes(int index) {
      return com.google.protobuf.ByteString.copyFromUtf8(
          stringListValue_.get(index));
    }
    private void ensureStringListValueIsMutable() {
      if (!stringListValue_.isModifiable()) {
        stringListValue_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(stringListValue_);
       }
    }
    /**
     * <code>repeated string stringListValue = 1;</code>
     */
    private void setStringListValue(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureStringListValueIsMutable();
      stringListValue_.set(index, value);
    }
    /**
     * <code>repeated string stringListValue = 1;</code>
     */
    private void addStringListValue(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureStringListValueIsMutable();
      stringListValue_.add(value);
    }
    /**
     * <code>repeated string stringListValue = 1;</code>
     */
    private void addAllStringListValue(
        java.lang.Iterable<java.lang.String> values) {
      ensureStringListValueIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, stringListValue_);
    }
    /**
     * <code>repeated string stringListValue = 1;</code>
     */
    private void clearStringListValue() {
      stringListValue_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }
    /**
     * <code>repeated string stringListValue = 1;</code>
     */
    private void addStringListValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureStringListValueIsMutable();
      stringListValue_.add(value.toStringUtf8());
    }

    public static final int DELIMITEDSTRINGVALUE_FIELD_NUMBER = 3;
    private java.lang.String delimitedStringValue_;
    /**
     * <code>optional string delimitedStringValue = 3;</code>
     */
    public java.lang.String getDelimitedStringValue() {
      return delimitedStringValue_;
    }
    /**
     * <code>optional string delimitedStringValue = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDelimitedStringValueBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(delimitedStringValue_);
    }
    /**
     * <code>optional string delimitedStringValue = 3;</code>
     */
    private void setDelimitedStringValue(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      delimitedStringValue_ = value;
    }
    /**
     * <code>optional string delimitedStringValue = 3;</code>
     */
    private void clearDelimitedStringValue() {
      
      delimitedStringValue_ = getDefaultInstance().getDelimitedStringValue();
    }
    /**
     * <code>optional string delimitedStringValue = 3;</code>
     */
    private void setDelimitedStringValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      delimitedStringValue_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < stringListValue_.size(); i++) {
        output.writeString(1, stringListValue_.get(i));
      }
      if (!delimitedStringValue_.isEmpty()) {
        output.writeString(3, getDelimitedStringValue());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < stringListValue_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeStringSizeNoTag(stringListValue_.get(i));
        }
        size += dataSize;
        size += 1 * getStringListValueList().size();
      }
      if (!delimitedStringValue_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getDelimitedStringValue());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static net.badata.protobuf.converter.proto.ResolverProto.ResolverTest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.badata.protobuf.converter.proto.ResolverProto.ResolverTest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.ResolverProto.ResolverTest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.badata.protobuf.converter.proto.ResolverProto.ResolverTest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.ResolverProto.ResolverTest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.badata.protobuf.converter.proto.ResolverProto.ResolverTest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.ResolverProto.ResolverTest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static net.badata.protobuf.converter.proto.ResolverProto.ResolverTest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.ResolverProto.ResolverTest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.badata.protobuf.converter.proto.ResolverProto.ResolverTest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.badata.protobuf.converter.proto.ResolverProto.ResolverTest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code net.badata.protobuf.converter.proto.ResolverTest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          net.badata.protobuf.converter.proto.ResolverProto.ResolverTest, Builder> implements
        // @@protoc_insertion_point(builder_implements:net.badata.protobuf.converter.proto.ResolverTest)
        net.badata.protobuf.converter.proto.ResolverProto.ResolverTestOrBuilder {
      // Construct using net.badata.protobuf.converter.proto.ResolverProto.ResolverTest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated string stringListValue = 1;</code>
       */
      public java.util.List<String>
          getStringListValueList() {
        return java.util.Collections.unmodifiableList(
            instance.getStringListValueList());
      }
      /**
       * <code>repeated string stringListValue = 1;</code>
       */
      public int getStringListValueCount() {
        return instance.getStringListValueCount();
      }
      /**
       * <code>repeated string stringListValue = 1;</code>
       */
      public java.lang.String getStringListValue(int index) {
        return instance.getStringListValue(index);
      }
      /**
       * <code>repeated string stringListValue = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStringListValueBytes(int index) {
        return instance.getStringListValueBytes(index);
      }
      /**
       * <code>repeated string stringListValue = 1;</code>
       */
      public Builder setStringListValue(
          int index, java.lang.String value) {
        copyOnWrite();
        instance.setStringListValue(index, value);
        return this;
      }
      /**
       * <code>repeated string stringListValue = 1;</code>
       */
      public Builder addStringListValue(
          java.lang.String value) {
        copyOnWrite();
        instance.addStringListValue(value);
        return this;
      }
      /**
       * <code>repeated string stringListValue = 1;</code>
       */
      public Builder addAllStringListValue(
          java.lang.Iterable<java.lang.String> values) {
        copyOnWrite();
        instance.addAllStringListValue(values);
        return this;
      }
      /**
       * <code>repeated string stringListValue = 1;</code>
       */
      public Builder clearStringListValue() {
        copyOnWrite();
        instance.clearStringListValue();
        return this;
      }
      /**
       * <code>repeated string stringListValue = 1;</code>
       */
      public Builder addStringListValueBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.addStringListValueBytes(value);
        return this;
      }

      /**
       * <code>optional string delimitedStringValue = 3;</code>
       */
      public java.lang.String getDelimitedStringValue() {
        return instance.getDelimitedStringValue();
      }
      /**
       * <code>optional string delimitedStringValue = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDelimitedStringValueBytes() {
        return instance.getDelimitedStringValueBytes();
      }
      /**
       * <code>optional string delimitedStringValue = 3;</code>
       */
      public Builder setDelimitedStringValue(
          java.lang.String value) {
        copyOnWrite();
        instance.setDelimitedStringValue(value);
        return this;
      }
      /**
       * <code>optional string delimitedStringValue = 3;</code>
       */
      public Builder clearDelimitedStringValue() {
        copyOnWrite();
        instance.clearDelimitedStringValue();
        return this;
      }
      /**
       * <code>optional string delimitedStringValue = 3;</code>
       */
      public Builder setDelimitedStringValueBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDelimitedStringValueBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:net.badata.protobuf.converter.proto.ResolverTest)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new net.badata.protobuf.converter.proto.ResolverProto.ResolverTest();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          stringListValue_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          net.badata.protobuf.converter.proto.ResolverProto.ResolverTest other = (net.badata.protobuf.converter.proto.ResolverProto.ResolverTest) arg1;
          stringListValue_= visitor.visitList(stringListValue_, other.stringListValue_);
          delimitedStringValue_ = visitor.visitString(!delimitedStringValue_.isEmpty(), delimitedStringValue_,
              !other.delimitedStringValue_.isEmpty(), other.delimitedStringValue_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();
                  if (!stringListValue_.isModifiable()) {
                    stringListValue_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(stringListValue_);
                  }
                  stringListValue_.add(s);
                  break;
                }
                case 26: {
                  String s = input.readStringRequireUtf8();

                  delimitedStringValue_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (net.badata.protobuf.converter.proto.ResolverProto.ResolverTest.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:net.badata.protobuf.converter.proto.ResolverTest)
    private static final net.badata.protobuf.converter.proto.ResolverProto.ResolverTest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ResolverTest();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static net.badata.protobuf.converter.proto.ResolverProto.ResolverTest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ResolverTest> PARSER;

    public static com.google.protobuf.Parser<ResolverTest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
